"use strict";

module.exports = {
  USD: {
    code: "USD",
    short: "$",
    symbol: "$",
    name: "US Dollar",
    plural: "US dollars",
    precision: 2,
    rounding: 0,
  },
  CAD: {
    code: "CAD",
    short: "CA$",
    symbol: "$",
    name: "Canadian Dollar",
    plural: "Canadian dollars",
    precision: 2,
    rounding: 0,
  },
  EUR: {
    code: "EUR",
    short: "€",
    symbol: "€",
    name: "Euro",
    plural: "euros",
    precision: 2,
    rounding: 0,
  },
  AED: {
    code: "AED",
    short: "AED",
    symbol: "د.إ.‏",
    name: "United Arab Emirates Dirham",
    plural: "UAE dirhams",
    precision: 2,
    rounding: 0,
  },
  AFN: {
    code: "AFN",
    short: "Af",
    symbol: "؋",
    name: "Afghan Afghani",
    plural: "Afghan Afghanis",
    precision: 0,
    rounding: 0,
  },
  ALL: {
    code: "ALL",
    short: "ALL",
    symbol: "Lek",
    name: "Albanian Lek",
    plural: "Albanian lekë",
    precision: 0,
    rounding: 0,
  },
  AMD: {
    code: "AMD",
    short: "AMD",
    symbol: "դր.",
    name: "Armenian Dram",
    plural: "Armenian drams",
    precision: 0,
    rounding: 0,
  },
  ARS: {
    code: "ARS",
    short: "AR$",
    symbol: "$",
    name: "Argentine Peso",
    plural: "Argentine pesos",
    precision: 2,
    rounding: 0,
  },
  AUD: {
    code: "AUD",
    short: "AU$",
    symbol: "$",
    name: "Australian Dollar",
    plural: "Australian dollars",
    precision: 2,
    rounding: 0,
  },
  AZN: {
    code: "AZN",
    short: "man.",
    symbol: "ман.",
    name: "Azerbaijani Manat",
    plural: "Azerbaijani manats",
    precision: 2,
    rounding: 0,
  },
  BAM: {
    code: "BAM",
    short: "KM",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    plural: "Bosnia-Herzegovina convertible marks",
    precision: 2,
    rounding: 0,
  },
  BDT: {
    code: "BDT",
    short: "Tk",
    symbol: "৳",
    name: "Bangladeshi Taka",
    plural: "Bangladeshi takas",
    precision: 2,
    rounding: 0,
  },
  BGN: {
    code: "BGN",
    short: "BGN",
    symbol: "лв.",
    name: "Bulgarian Lev",
    plural: "Bulgarian leva",
    precision: 2,
    rounding: 0,
  },
  BHD: {
    code: "BHD",
    short: "BD",
    symbol: "د.ب.‏",
    name: "Bahraini Dinar",
    plural: "Bahraini dinars",
    precision: 3,
    rounding: 0,
  },
  BIF: {
    code: "BIF",
    short: "FBu",
    symbol: "FBu",
    name: "Burundian Franc",
    plural: "Burundian francs",
    precision: 0,
    rounding: 0,
  },
  BND: {
    code: "BND",
    short: "BN$",
    symbol: "$",
    name: "Brunei Dollar",
    plural: "Brunei dollars",
    precision: 2,
    rounding: 0,
  },
  BOB: {
    code: "BOB",
    short: "Bs",
    symbol: "Bs",
    name: "Bolivian Boliviano",
    plural: "Bolivian bolivianos",
    precision: 2,
    rounding: 0,
  },
  BRL: {
    code: "BRL",
    short: "R$",
    symbol: "R$",
    name: "Brazilian Real",
    plural: "Brazilian reals",
    precision: 2,
    rounding: 0,
  },
  BWP: {
    code: "BWP",
    short: "BWP",
    symbol: "P",
    name: "Botswanan Pula",
    plural: "Botswanan pulas",
    precision: 2,
    rounding: 0,
  },
  BYR: {
    code: "BYR",
    short: "BYR",
    symbol: "BYR",
    name: "Belarusian Ruble",
    plural: "Belarusian rubles",
    precision: 0,
    rounding: 0,
  },
  BZD: {
    code: "BZD",
    short: "BZ$",
    symbol: "$",
    name: "Belize Dollar",
    plural: "Belize dollars",
    precision: 2,
    rounding: 0,
  },
  CDF: {
    code: "CDF",
    short: "CDF",
    symbol: "FrCD",
    name: "Congolese Franc",
    plural: "Congolese francs",
    precision: 2,
    rounding: 0,
  },
  CHF: {
    code: "CHF",
    short: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    plural: "Swiss francs",
    precision: 2,
    rounding: 0.05,
  },
  CLP: {
    code: "CLP",
    short: "CL$",
    symbol: "$",
    name: "Chilean Peso",
    plural: "Chilean pesos",
    precision: 0,
    rounding: 0,
  },
  CNY: {
    code: "CNY",
    short: "CN¥",
    symbol: "CN¥",
    name: "Chinese Yuan",
    plural: "Chinese yuan",
    precision: 2,
    rounding: 0,
  },
  COP: {
    code: "COP",
    short: "CO$",
    symbol: "$",
    name: "Colombian Peso",
    plural: "Colombian pesos",
    precision: 0,
    rounding: 0,
  },
  CRC: {
    code: "CRC",
    short: "₡",
    symbol: "₡",
    name: "Costa Rican Colón",
    plural: "Costa Rican colóns",
    precision: 0,
    rounding: 0,
  },
  CVE: {
    code: "CVE",
    short: "CV$",
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    plural: "Cape Verdean escudos",
    precision: 2,
    rounding: 0,
  },
  CZK: {
    code: "CZK",
    short: "Kč",
    symbol: "Kč",
    name: "Czech Republic Koruna",
    plural: "Czech Republic korunas",
    precision: 2,
    rounding: 0,
  },
  DJF: {
    code: "DJF",
    short: "Fdj",
    symbol: "Fdj",
    name: "Djiboutian Franc",
    plural: "Djiboutian francs",
    precision: 0,
    rounding: 0,
  },
  DKK: {
    code: "DKK",
    short: "Dkr",
    symbol: "kr",
    name: "Danish Krone",
    plural: "Danish kroner",
    precision: 2,
    rounding: 0,
  },
  DOP: {
    code: "DOP",
    short: "RD$",
    symbol: "RD$",
    name: "Dominican Peso",
    plural: "Dominican pesos",
    precision: 2,
    rounding: 0,
  },
  DZD: {
    code: "DZD",
    short: "DA",
    symbol: "د.ج.‏",
    name: "Algerian Dinar",
    plural: "Algerian dinars",
    precision: 2,
    rounding: 0,
  },
  EEK: {
    code: "EEK",
    short: "Ekr",
    symbol: "kr",
    name: "Estonian Kroon",
    plural: "Estonian kroons",
    precision: 2,
    rounding: 0,
  },
  EGP: {
    code: "EGP",
    short: "EGP",
    symbol: "ج.م.‏",
    name: "Egyptian Pound",
    plural: "Egyptian pounds",
    precision: 2,
    rounding: 0,
  },
  ERN: {
    code: "ERN",
    short: "Nfk",
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    plural: "Eritrean nakfas",
    precision: 2,
    rounding: 0,
  },
  ETB: {
    code: "ETB",
    short: "Br",
    symbol: "Br",
    name: "Ethiopian Birr",
    plural: "Ethiopian birrs",
    precision: 2,
    rounding: 0,
  },
  GBP: {
    code: "GBP",
    short: "£",
    symbol: "£",
    name: "British Pound Sterling",
    plural: "British pounds sterling",
    precision: 2,
    rounding: 0,
  },
  GEL: {
    code: "GEL",
    short: "GEL",
    symbol: "GEL",
    name: "Georgian Lari",
    plural: "Georgian laris",
    precision: 2,
    rounding: 0,
  },
  GHS: {
    code: "GHS",
    short: "GH₵",
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    plural: "Ghanaian cedis",
    precision: 2,
    rounding: 0,
  },
  GNF: {
    code: "GNF",
    short: "FG",
    symbol: "FG",
    name: "Guinean Franc",
    plural: "Guinean francs",
    precision: 0,
    rounding: 0,
  },
  GTQ: {
    code: "GTQ",
    short: "GTQ",
    symbol: "Q",
    name: "Guatemalan Quetzal",
    plural: "Guatemalan quetzals",
    precision: 2,
    rounding: 0,
  },
  HKD: {
    code: "HKD",
    short: "HK$",
    symbol: "$",
    name: "Hong Kong Dollar",
    plural: "Hong Kong dollars",
    precision: 2,
    rounding: 0,
  },
  HNL: {
    code: "HNL",
    short: "HNL",
    symbol: "L",
    name: "Honduran Lempira",
    plural: "Honduran lempiras",
    precision: 2,
    rounding: 0,
  },
  HRK: {
    code: "HRK",
    short: "kn",
    symbol: "kn",
    name: "Croatian Kuna",
    plural: "Croatian kunas",
    precision: 2,
    rounding: 0,
  },
  HUF: {
    code: "HUF",
    short: "Ft",
    symbol: "Ft",
    name: "Hungarian Forint",
    plural: "Hungarian forints",
    precision: 0,
    rounding: 0,
  },
  IDR: {
    code: "IDR",
    short: "Rp",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    plural: "Indonesian rupiahs",
    precision: 0,
    rounding: 0,
  },
  ILS: {
    code: "ILS",
    short: "₪",
    symbol: "₪",
    name: "Israeli New Sheqel",
    plural: "Israeli new sheqels",
    precision: 2,
    rounding: 0,
  },
  INR: {
    code: "INR",
    short: "Rs",
    symbol: "টকা",
    name: "Indian Rupee",
    plural: "Indian rupees",
    precision: 2,
    rounding: 0,
  },
  IQD: {
    code: "IQD",
    short: "IQD",
    symbol: "د.ع.‏",
    name: "Iraqi Dinar",
    plural: "Iraqi dinars",
    precision: 0,
    rounding: 0,
  },
  IRR: {
    code: "IRR",
    short: "IRR",
    symbol: "﷼",
    name: "Iranian Rial",
    plural: "Iranian rials",
    precision: 0,
    rounding: 0,
  },
  ISK: {
    code: "ISK",
    short: "Ikr",
    symbol: "kr",
    name: "Icelandic Króna",
    plural: "Icelandic krónur",
    precision: 0,
    rounding: 0,
  },
  JMD: {
    code: "JMD",
    short: "J$",
    symbol: "$",
    name: "Jamaican Dollar",
    plural: "Jamaican dollars",
    precision: 2,
    rounding: 0,
  },
  JOD: {
    code: "JOD",
    short: "JD",
    symbol: "د.أ.‏",
    name: "Jordanian Dinar",
    plural: "Jordanian dinars",
    precision: 3,
    rounding: 0,
  },
  JPY: {
    code: "JPY",
    short: "¥",
    symbol: "￥",
    name: "Japanese Yen",
    plural: "Japanese yen",
    precision: 0,
    rounding: 0,
  },
  KES: {
    code: "KES",
    short: "Ksh",
    symbol: "Ksh",
    name: "Kenyan Shilling",
    plural: "Kenyan shillings",
    precision: 2,
    rounding: 0,
  },
  KHR: {
    code: "KHR",
    short: "KHR",
    symbol: "៛",
    name: "Cambodian Riel",
    plural: "Cambodian riels",
    precision: 2,
    rounding: 0,
  },
  KMF: {
    code: "KMF",
    short: "CF",
    symbol: "FC",
    name: "Comorian Franc",
    plural: "Comorian francs",
    precision: 0,
    rounding: 0,
  },
  KRW: {
    code: "KRW",
    short: "₩",
    symbol: "₩",
    name: "South Korean Won",
    plural: "South Korean won",
    precision: 0,
    rounding: 0,
  },
  KWD: {
    code: "KWD",
    short: "KD",
    symbol: "د.ك.‏",
    name: "Kuwaiti Dinar",
    plural: "Kuwaiti dinars",
    precision: 3,
    rounding: 0,
  },
  KZT: {
    code: "KZT",
    short: "KZT",
    symbol: "тңг.",
    name: "Kazakhstani Tenge",
    plural: "Kazakhstani tenges",
    precision: 2,
    rounding: 0,
  },
  LBP: {
    code: "LBP",
    short: "LB£",
    symbol: "ل.ل.‏",
    name: "Lebanese Pound",
    plural: "Lebanese pounds",
    precision: 0,
    rounding: 0,
  },
  LKR: {
    code: "LKR",
    short: "SLRs",
    symbol: "SL Re",
    name: "Sri Lankan Rupee",
    plural: "Sri Lankan rupees",
    precision: 2,
    rounding: 0,
  },
  LTL: {
    code: "LTL",
    short: "Lt",
    symbol: "Lt",
    name: "Lithuanian Litas",
    plural: "Lithuanian litai",
    precision: 2,
    rounding: 0,
  },
  LVL: {
    code: "LVL",
    short: "Ls",
    symbol: "Ls",
    name: "Latvian Lats",
    plural: "Latvian lati",
    precision: 2,
    rounding: 0,
  },
  LYD: {
    code: "LYD",
    short: "LD",
    symbol: "د.ل.‏",
    name: "Libyan Dinar",
    plural: "Libyan dinars",
    precision: 3,
    rounding: 0,
  },
  MAD: {
    code: "MAD",
    short: "MAD",
    symbol: "د.م.‏",
    name: "Moroccan Dirham",
    plural: "Moroccan dirhams",
    precision: 2,
    rounding: 0,
  },
  MDL: {
    code: "MDL",
    short: "MDL",
    symbol: "MDL",
    name: "Moldovan Leu",
    plural: "Moldovan lei",
    precision: 2,
    rounding: 0,
  },
  MGA: {
    code: "MGA",
    short: "MGA",
    symbol: "MGA",
    name: "Malagasy Ariary",
    plural: "Malagasy Ariaries",
    precision: 0,
    rounding: 0,
  },
  MKD: {
    code: "MKD",
    short: "MKD",
    symbol: "MKD",
    name: "Macedonian Denar",
    plural: "Macedonian denari",
    precision: 2,
    rounding: 0,
  },
  MMK: {
    code: "MMK",
    short: "MMK",
    symbol: "K",
    name: "Myanma Kyat",
    plural: "Myanma kyats",
    precision: 0,
    rounding: 0,
  },
  MOP: {
    code: "MOP",
    short: "MOP$",
    symbol: "MOP$",
    name: "Macanese Pataca",
    plural: "Macanese patacas",
    precision: 2,
    rounding: 0,
  },
  MUR: {
    code: "MUR",
    short: "MURs",
    symbol: "MURs",
    name: "Mauritian Rupee",
    plural: "Mauritian rupees",
    precision: 0,
    rounding: 0,
  },
  MXN: {
    code: "MXN",
    short: "MX$",
    symbol: "$",
    name: "Mexican Peso",
    plural: "Mexican pesos",
    precision: 2,
    rounding: 0,
  },
  MYR: {
    code: "MYR",
    short: "RM",
    symbol: "RM",
    name: "Malaysian Ringgit",
    plural: "Malaysian ringgits",
    precision: 2,
    rounding: 0,
  },
  MZN: {
    code: "MZN",
    short: "MTn",
    symbol: "MTn",
    name: "Mozambican Metical",
    plural: "Mozambican meticals",
    precision: 2,
    rounding: 0,
  },
  NAD: {
    code: "NAD",
    short: "N$",
    symbol: "N$",
    name: "Namibian Dollar",
    plural: "Namibian dollars",
    precision: 2,
    rounding: 0,
  },
  NGN: {
    code: "NGN",
    short: "₦",
    symbol: "₦",
    name: "Nigerian Naira",
    plural: "Nigerian nairas",
    precision: 2,
    rounding: 0,
  },
  NIO: {
    code: "NIO",
    short: "C$",
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    plural: "Nicaraguan córdobas",
    precision: 2,
    rounding: 0,
  },
  NOK: {
    code: "NOK",
    short: "Nkr",
    symbol: "kr",
    name: "Norwegian Krone",
    plural: "Norwegian kroner",
    precision: 2,
    rounding: 0,
  },
  NPR: {
    code: "NPR",
    short: "NPRs",
    symbol: "नेरू",
    name: "Nepalese Rupee",
    plural: "Nepalese rupees",
    precision: 2,
    rounding: 0,
  },
  NZD: {
    code: "NZD",
    short: "NZ$",
    symbol: "$",
    name: "New Zealand Dollar",
    plural: "New Zealand dollars",
    precision: 2,
    rounding: 0,
  },
  OMR: {
    code: "OMR",
    short: "OMR",
    symbol: "ر.ع.‏",
    name: "Omani Rial",
    plural: "Omani rials",
    precision: 3,
    rounding: 0,
  },
  PAB: {
    code: "PAB",
    short: "B/.",
    symbol: "B/.",
    name: "Panamanian Balboa",
    plural: "Panamanian balboas",
    precision: 2,
    rounding: 0,
  },
  PEN: {
    code: "PEN",
    short: "S/.",
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    plural: "Peruvian nuevos soles",
    precision: 2,
    rounding: 0,
  },
  PHP: {
    code: "PHP",
    short: "₱",
    symbol: "₱",
    name: "Philippine Peso",
    plural: "Philippine pesos",
    precision: 2,
    rounding: 0,
  },
  PKR: {
    code: "PKR",
    short: "PKRs",
    symbol: "₨",
    name: "Pakistani Rupee",
    plural: "Pakistani rupees",
    precision: 0,
    rounding: 0,
  },
  PLN: {
    code: "PLN",
    short: "zł",
    symbol: "zł",
    name: "Polish Zloty",
    plural: "Polish zlotys",
    precision: 2,
    rounding: 0,
  },
  PYG: {
    code: "PYG",
    short: "₲",
    symbol: "₲",
    name: "Paraguayan Guarani",
    plural: "Paraguayan guaranis",
    precision: 0,
    rounding: 0,
  },
  QAR: {
    code: "QAR",
    short: "QR",
    symbol: "ر.ق.‏",
    name: "Qatari Rial",
    plural: "Qatari rials",
    precision: 2,
    rounding: 0,
  },
  RON: {
    code: "RON",
    short: "RON",
    symbol: "RON",
    name: "Romanian Leu",
    plural: "Romanian lei",
    precision: 2,
    rounding: 0,
  },
  RSD: {
    code: "RSD",
    short: "din.",
    symbol: "дин.",
    name: "Serbian Dinar",
    plural: "Serbian dinars",
    precision: 0,
    rounding: 0,
  },
  RUB: {
    code: "RUB",
    short: "RUB",
    symbol: "руб.",
    name: "Russian Ruble",
    plural: "Russian rubles",
    precision: 2,
    rounding: 0,
  },
  RWF: {
    code: "RWF",
    short: "RWF",
    symbol: "FR",
    name: "Rwandan Franc",
    plural: "Rwandan francs",
    precision: 0,
    rounding: 0,
  },
  SAR: {
    code: "SAR",
    short: "SR",
    symbol: "ر.س.‏",
    name: "Saudi Riyal",
    plural: "Saudi riyals",
    precision: 2,
    rounding: 0,
  },
  SDG: {
    code: "SDG",
    short: "SDG",
    symbol: "SDG",
    name: "Sudanese Pound",
    plural: "Sudanese pounds",
    precision: 2,
    rounding: 0,
  },
  SEK: {
    code: "SEK",
    short: "Skr",
    symbol: "kr",
    name: "Swedish Krona",
    plural: "Swedish kronor",
    precision: 2,
    rounding: 0,
  },
  SGD: {
    code: "SGD",
    short: "S$",
    symbol: "$",
    name: "Singapore Dollar",
    plural: "Singapore dollars",
    precision: 2,
    rounding: 0,
  },
  SOS: {
    code: "SOS",
    short: "Ssh",
    symbol: "Ssh",
    name: "Somali Shilling",
    plural: "Somali shillings",
    precision: 0,
    rounding: 0,
  },
  SYP: {
    code: "SYP",
    short: "SY£",
    symbol: "ل.س.‏",
    name: "Syrian Pound",
    plural: "Syrian pounds",
    precision: 0,
    rounding: 0,
  },
  THB: {
    code: "THB",
    short: "฿",
    symbol: "฿",
    name: "Thai Baht",
    plural: "Thai baht",
    precision: 2,
    rounding: 0,
  },
  TND: {
    code: "TND",
    short: "DT",
    symbol: "د.ت.‏",
    name: "Tunisian Dinar",
    plural: "Tunisian dinars",
    precision: 3,
    rounding: 0,
  },
  TOP: {
    code: "TOP",
    short: "T$",
    symbol: "T$",
    name: "Tongan Paʻanga",
    plural: "Tongan paʻanga",
    precision: 2,
    rounding: 0,
  },
  TRY: {
    code: "TRY",
    short: "TL",
    symbol: "TL",
    name: "Turkish Lira",
    plural: "Turkish Lira",
    precision: 2,
    rounding: 0,
  },
  TTD: {
    code: "TTD",
    short: "TT$",
    symbol: "$",
    name: "Trinidad and Tobago Dollar",
    plural: "Trinidad and Tobago dollars",
    precision: 2,
    rounding: 0,
  },
  TWD: {
    code: "TWD",
    short: "NT$",
    symbol: "NT$",
    name: "New Taiwan Dollar",
    plural: "New Taiwan dollars",
    precision: 2,
    rounding: 0,
  },
  TZS: {
    code: "TZS",
    short: "TSh",
    symbol: "TSh",
    name: "Tanzanian Shilling",
    plural: "Tanzanian shillings",
    precision: 0,
    rounding: 0,
  },
  UAH: {
    code: "UAH",
    short: "₴",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    plural: "Ukrainian hryvnias",
    precision: 2,
    rounding: 0,
  },
  UGX: {
    code: "UGX",
    short: "USh",
    symbol: "USh",
    name: "Ugandan Shilling",
    plural: "Ugandan shillings",
    precision: 0,
    rounding: 0,
  },
  UYU: {
    code: "UYU",
    short: "$U",
    symbol: "$",
    name: "Uruguayan Peso",
    plural: "Uruguayan pesos",
    precision: 2,
    rounding: 0,
  },
  UZS: {
    code: "UZS",
    short: "UZS",
    symbol: "UZS",
    name: "Uzbekistan Som",
    plural: "Uzbekistan som",
    precision: 0,
    rounding: 0,
  },
  VEF: {
    code: "VEF",
    short: "Bs.F.",
    symbol: "Bs.F.",
    name: "Venezuelan Bolívar",
    plural: "Venezuelan bolívars",
    precision: 2,
    rounding: 0,
  },
  VND: {
    code: "VND",
    short: "₫",
    symbol: "₫",
    name: "Vietnamese Dong",
    plural: "Vietnamese dong",
    precision: 0,
    rounding: 0,
  },
  XAF: {
    code: "XAF",
    short: "FCFA",
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    plural: "CFA francs BEAC",
    precision: 0,
    rounding: 0,
  },
  XOF: {
    code: "XOF",
    short: "CFA",
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    plural: "CFA francs BCEAO",
    precision: 0,
    rounding: 0,
  },
  YER: {
    code: "YER",
    short: "YR",
    symbol: "ر.ي.‏",
    name: "Yemeni Rial",
    plural: "Yemeni rials",
    precision: 0,
    rounding: 0,
  },
  ZAR: {
    code: "ZAR",
    short: "R",
    symbol: "R",
    name: "South African Rand",
    plural: "South African rand",
    precision: 2,
    rounding: 0,
  },
  ZMK: {
    code: "ZMK",
    short: "ZK",
    symbol: "ZK",
    name: "Zambian Kwacha",
    plural: "Zambian kwachas",
    precision: 0,
    rounding: 0,
  },
};
