"use strict";

module.exports = {
  BTC: {
    code: "BTC",
    symbol: "₿",
    name: "Bitcoin",
    precision: 4,
    rounding: 0,
  },
  ETH: {
    code: "ETH",
    symbol: undefined,
    name: "Ethereum",
    precision: 4,
    rounding: 0,
  },
  BCH: {
    code: "BCH",
    symbol: undefined,
    name: "Bitcoin Cash",
    precision: 4,
    rounding: 0,
  },
  XRP: {
    code: "XRP",
    symbol: undefined,
    name: "Ripple",
    precision: 4,
    rounding: 0,
  },
  LTC: {
    code: "LTC",
    symbol: undefined,
    name: "Litecoin",
    precision: 4,
    rounding: 0,
  },
  DASH: {
    code: "DASH",
    symbol: undefined,
    name: "Dash",
    precision: 4,
    rounding: 0,
  },
  XEM: {
    code: "XEM",
    symbol: undefined,
    name: "NEM",
    precision: 4,
    rounding: 0,
  },
  IOT: {
    code: "IOT",
    symbol: undefined,
    name: "IOTA",
    precision: 4,
    rounding: 0,
  },
  XMR: {
    code: "XMR",
    symbol: undefined,
    name: "Monero",
    precision: 4,
    rounding: 0,
  },
  NEO: {
    code: "NEO",
    symbol: undefined,
    name: "NEO",
    precision: 4,
    rounding: 0,
  },
  ETC: {
    code: "ETC",
    symbol: undefined,
    name: "Ethereum Classic",
    precision: 4,
    rounding: 0,
  },
  HSR: {
    code: "HSR",
    symbol: undefined,
    name: "Hshare",
    precision: 4,
    rounding: 0,
  },
  QTUM: {
    code: "QTUM",
    symbol: undefined,
    name: "Qtum",
    precision: 4,
    rounding: 0,
  },
  OMG: {
    code: "OMG",
    symbol: undefined,
    name: "OmiseGo",
    precision: 4,
    rounding: 0,
  },
  STRAT: {
    code: "STRAT",
    symbol: undefined,
    name: "Stratis",
    precision: 4,
    rounding: 0,
  },
};
