"use strict";

module.exports = {
  BTC: {
    code: "BTC",
    symbol: "₿",
    name: "Bitcoin",
    precision: 4,
    rounding: 0,
  },
  ETH: {
    code: "ETH",
    symbol: undefined,
    name: "Ethereum",
    precision: 4,
    rounding: 0,
  },
  BCH: {
    code: "BCH",
    symbol: undefined,
    name: "Bitcoin Cash",
    precision: 4,
    rounding: 0,
  },
  XRP: {
    code: "XRP",
    symbol: undefined,
    name: "Ripple",
    precision: 4,
    rounding: 0,
  },
  LTC: {
    code: "LTC",
    symbol: undefined,
    name: "Litecoin",
    precision: 4,
    rounding: 0,
  },
  DASH: {
    code: "DASH",
    symbol: undefined,
    name: "Dash",
    precision: 4,
    rounding: 0,
  },
  XEM: {
    code: "XEM",
    symbol: undefined,
    name: "NEM",
    precision: 4,
    rounding: 0,
  },
  IOT: {
    code: "IOT",
    symbol: undefined,
    name: "IOTA",
    precision: 4,
    rounding: 0,
  },
  XMR: {
    code: "XMR",
    symbol: undefined,
    name: "Monero",
    precision: 4,
    rounding: 0,
  },
  NEO: {
    code: "NEO",
    symbol: undefined,
    name: "NEO",
    precision: 4,
    rounding: 0,
  },
  ETC: {
    code: "ETC",
    symbol: undefined,
    name: "Ethereum Classic",
    precision: 4,
    rounding: 0,
  },
  HSR: {
    code: "HSR",
    symbol: undefined,
    name: "Hshare",
    precision: 4,
    rounding: 0,
  },
  QTUM: {
    code: "QTUM",
    symbol: undefined,
    name: "Qtum",
    precision: 4,
    rounding: 0,
  },
  OMG: {
    code: "OMG",
    symbol: undefined,
    name: "OmiseGo",
    precision: 4,
    rounding: 0,
  },
  STRAT: {
    code: "STRAT",
    symbol: undefined,
    name: "Stratis",
    precision: 4,
    rounding: 0,
  },
  LSK: {
    code: "LSK",
    symbol: undefined,
    name: "Lisk",
    precision: 4,
    rounding: 0,
  },
  ZEC: {
    code: "ZEC",
    symbol: undefined,
    name: "Zcash",
    precision: 4,
    rounding: 0,
  },
  WAVES: {
    code: "WAVES",
    symbol: undefined,
    name: "Waves",
    precision: 4,
    rounding: 0,
  },
  PAY: {
    code: "PAY",
    symbol: undefined,
    name: "TenX",
    precision: 4,
    rounding: 0,
  },
  EOS: {
    code: "EOS",
    symbol: undefined,
    name: "EOS",
    precision: 4,
    rounding: 0,
  },
  STEEM: {
    code: "STEEM",
    symbol: undefined,
    name: "Steem",
    precision: 4,
    rounding: 0,
  },
  BTS: {
    code: "BTS",
    symbol: undefined,
    name: "BitShares",
    precision: 4,
    rounding: 0,
  },
  BCN: {
    code: "BCN",
    symbol: undefined,
    name: "Bytecoin",
    precision: 4,
    rounding: 0,
  },
  USDT: {
    code: "USDT",
    symbol: undefined,
    name: "Tether",
    precision: 4,
    rounding: 0,
  },
  MAID: {
    code: "MAID",
    symbol: undefined,
    name: "MaidSafeCoin",
    precision: 4,
    rounding: 0,
  },
  REP: {
    code: "REP",
    symbol: undefined,
    name: "Augur",
    precision: 4,
    rounding: 0,
  },
  ARK: {
    code: "ARK",
    symbol: undefined,
    name: "Ark",
    precision: 4,
    rounding: 0,
  },
  FCT: {
    code: "FCT",
    symbol: undefined,
    name: "Factom",
    precision: 4,
    rounding: 0,
  },
  GNT: {
    code: "GNT",
    symbol: undefined,
    name: "Golem",
    precision: 4,
    rounding: 0,
  },
  SC: {
    code: "SC",
    symbol: undefined,
    name: "Siacoin",
    precision: 4,
    rounding: 0,
  },
  XLM: {
    code: "XLM",
    symbol: undefined,
    name: "Stellar Lumens",
    precision: 4,
    rounding: 0,
  },
  MCO: {
    code: "MCO",
    symbol: undefined,
    name: "Monaco",
    precision: 4,
    rounding: 0,
  },
  BAT: {
    code: "BAT",
    symbol: undefined,
    name: "Basic Attenti...",
    precision: 4,
    rounding: 0,
  },
  GBYTE: {
    code: "GBYTE",
    symbol: undefined,
    name: "Byteball",
    precision: 4,
    rounding: 0,
  },
  DCR: {
    code: "DCR",
    symbol: undefined,
    name: "Decred",
    precision: 4,
    rounding: 0,
  },
  VERI: {
    code: "VERI",
    symbol: undefined,
    name: "Veritaseum",
    precision: 4,
    rounding: 0,
  },
  ICN: {
    code: "ICN",
    symbol: undefined,
    name: "Iconomi",
    precision: 4,
    rounding: 0,
  },
  GNO: {
    code: "GNO",
    symbol: undefined,
    name: "Gnosis",
    precision: 4,
    rounding: 0,
  },
  BNB: {
    code: "BNB",
    symbol: undefined,
    name: "Binance Coin",
    precision: 4,
    rounding: 0,
  },
  DOGE: {
    code: "DOGE",
    symbol: undefined,
    name: "Dogecoin",
    precision: 4,
    rounding: 0,
  },
  MTL: {
    code: "MTL",
    symbol: undefined,
    name: "Metal",
    precision: 4,
    rounding: 0,
  },
  DGD: {
    code: "DGD",
    symbol: undefined,
    name: "DigixDAO",
    precision: 4,
    rounding: 0,
  },
  CVC: {
    code: "CVC",
    symbol: undefined,
    name: "Civic",
    precision: 4,
    rounding: 0,
  },
  ZRX: {
    code: "ZRX",
    symbol: undefined,
    name: "0x",
    precision: 4,
    rounding: 0,
  },
  KMD: {
    code: "KMD",
    symbol: undefined,
    name: "Komodo",
    precision: 4,
    rounding: 0,
  },
  SNT: {
    code: "SNT",
    symbol: undefined,
    name: "Status",
    precision: 4,
    rounding: 0,
  },
  PIVX: {
    code: "PIVX",
    symbol: undefined,
    name: "PIVX",
    precision: 4,
    rounding: 0,
  },
  PPT: {
    code: "PPT",
    symbol: undefined,
    name: "Populous",
    precision: 4,
    rounding: 0,
  },
  GAS: {
    code: "GAS",
    symbol: undefined,
    name: "Gas",
    precision: 4,
    rounding: 0,
  },
  "808": {
    code: "808",
    symbol: undefined,
    name: "808Coin",
    precision: 4,
    rounding: 0,
  },
  GAME: {
    code: "GAME",
    symbol: undefined,
    name: "GameCredits",
    precision: 4,
    rounding: 0,
  },
  ARDR: {
    code: "ARDR",
    symbol: undefined,
    name: "Ardor",
    precision: 4,
    rounding: 0,
  },
  MCAP: {
    code: "MCAP",
    symbol: undefined,
    name: "MCAP",
    precision: 4,
    rounding: 0,
  },
  DGB: {
    code: "DGB",
    symbol: undefined,
    name: "DigiByte",
    precision: 4,
    rounding: 0,
  },
  BNT: {
    code: "BNT",
    symbol: undefined,
    name: "Bancor",
    precision: 4,
    rounding: 0,
  },
  BTM: {
    code: "BTM",
    symbol: undefined,
    name: "Bytom",
    precision: 4,
    rounding: 0,
  },
  NXT: {
    code: "NXT",
    symbol: undefined,
    name: "Nxt",
    precision: 4,
    rounding: 0,
  },
  FUN: {
    code: "FUN",
    symbol: undefined,
    name: "FunFair",
    precision: 4,
    rounding: 0,
  },
  NXS: {
    code: "NXS",
    symbol: undefined,
    name: "Nexus",
    precision: 4,
    rounding: 0,
  },
  NLC2: {
    code: "NLC2",
    symbol: undefined,
    name: "NoLimitCoin",
    precision: 4,
    rounding: 0,
  },
  ANT: {
    code: "ANT",
    symbol: undefined,
    name: "Aragon",
    precision: 4,
    rounding: 0,
  },
  LKK: {
    code: "LKK",
    symbol: undefined,
    name: "Lykke",
    precision: 4,
    rounding: 0,
  },
  UBQ: {
    code: "UBQ",
    symbol: undefined,
    name: "Ubiq",
    precision: 4,
    rounding: 0,
  },
  CFI: {
    code: "CFI",
    symbol: undefined,
    name: "Cofound.it",
    precision: 4,
    rounding: 0,
  },
  BLOCK: {
    code: "BLOCK",
    symbol: undefined,
    name: "Blocknet",
    precision: 4,
    rounding: 0,
  },
  MGO: {
    code: "MGO",
    symbol: undefined,
    name: "MobileGo",
    precision: 4,
    rounding: 0,
  },
  STORJ: {
    code: "STORJ",
    symbol: undefined,
    name: "Storj",
    precision: 4,
    rounding: 0,
  },
  TNT: {
    code: "TNT",
    symbol: undefined,
    name: "Tierion",
    precision: 4,
    rounding: 0,
  },
  BTCD: {
    code: "BTCD",
    symbol: undefined,
    name: "BitcoinDark",
    precision: 4,
    rounding: 0,
  },
  ICO: {
    code: "ICO",
    symbol: undefined,
    name: "ICO",
    precision: 4,
    rounding: 0,
  },
  SNGLS: {
    code: "SNGLS",
    symbol: undefined,
    name: "SingularDTV",
    precision: 4,
    rounding: 0,
  },
  SYS: {
    code: "SYS",
    symbol: undefined,
    name: "SysCoin",
    precision: 4,
    rounding: 0,
  },
  PART: {
    code: "PART",
    symbol: undefined,
    name: "Particl",
    precision: 4,
    rounding: 0,
  },
  ETP: {
    code: "ETP",
    symbol: undefined,
    name: "Metaverse ETP",
    precision: 4,
    rounding: 0,
  },
  DNT: {
    code: "DNT",
    symbol: undefined,
    name: "district0x",
    precision: 4,
    rounding: 0,
  },
  TKN: {
    code: "TKN",
    symbol: undefined,
    name: "TokenCard",
    precision: 4,
    rounding: 0,
  },
  ADX: {
    code: "ADX",
    symbol: undefined,
    name: "AdEx",
    precision: 4,
    rounding: 0,
  },
  WINGS: {
    code: "WINGS",
    symbol: undefined,
    name: "Wings",
    precision: 4,
    rounding: 0,
  },
  XAS: {
    code: "XAS",
    symbol: undefined,
    name: "Asch",
    precision: 4,
    rounding: 0,
  },
  EDG: {
    code: "EDG",
    symbol: undefined,
    name: "Edgeless",
    precision: 4,
    rounding: 0,
  },
  PLR: {
    code: "PLR",
    symbol: undefined,
    name: "Pillar",
    precision: 4,
    rounding: 0,
  },
  BQX: {
    code: "BQX",
    symbol: undefined,
    name: "Bitquence",
    precision: 4,
    rounding: 0,
  },
  DCT: {
    code: "DCT",
    symbol: undefined,
    name: "DECENT",
    precision: 4,
    rounding: 0,
  },
  "1ST": {
    code: "1ST",
    symbol: undefined,
    name: "FirstBlood",
    precision: 4,
    rounding: 0,
  },
  STX: {
    code: "STX",
    symbol: undefined,
    name: "Stox",
    precision: 4,
    rounding: 0,
  },
  EMC: {
    code: "EMC",
    symbol: undefined,
    name: "Emercoin",
    precision: 4,
    rounding: 0,
  },
  RLC: {
    code: "RLC",
    symbol: undefined,
    name: "iExec RLC",
    precision: 4,
    rounding: 0,
  },
  CDT: {
    code: "CDT",
    symbol: undefined,
    name: "CoinDash",
    precision: 4,
    rounding: 0,
  },
  PPC: {
    code: "PPC",
    symbol: undefined,
    name: "Peercoin",
    precision: 4,
    rounding: 0,
  },
  XVG: {
    code: "XVG",
    symbol: undefined,
    name: "Verge",
    precision: 4,
    rounding: 0,
  },
  MLN: {
    code: "MLN",
    symbol: undefined,
    name: "Melon",
    precision: 4,
    rounding: 0,
  },
  LEO: {
    code: "LEO",
    symbol: undefined,
    name: "LEOcoin",
    precision: 4,
    rounding: 0,
  },
  NMR: {
    code: "NMR",
    symbol: undefined,
    name: "Numeraire",
    precision: 4,
    rounding: 0,
  },
  XEL: {
    code: "XEL",
    symbol: undefined,
    name: "Elastic",
    precision: 4,
    rounding: 0,
  },
  FRST: {
    code: "FRST",
    symbol: undefined,
    name: "FirstCoin",
    precision: 4,
    rounding: 0,
  },
  ROUND: {
    code: "ROUND",
    symbol: undefined,
    name: "Round",
    precision: 4,
    rounding: 0,
  },
  XCP: {
    code: "XCP",
    symbol: undefined,
    name: "Counterparty",
    precision: 4,
    rounding: 0,
  },
  IOC: {
    code: "IOC",
    symbol: undefined,
    name: "I/O Coin",
    precision: 4,
    rounding: 0,
  },
  NLG: {
    code: "NLG",
    symbol: undefined,
    name: "Gulden",
    precision: 4,
    rounding: 0,
  },
  NAV: {
    code: "NAV",
    symbol: undefined,
    name: "NAV Coin",
    precision: 4,
    rounding: 0,
  },
  TAAS: {
    code: "TAAS",
    symbol: undefined,
    name: "TaaS",
    precision: 4,
    rounding: 0,
  },
  XZC: {
    code: "XZC",
    symbol: undefined,
    name: "ZCoin",
    precision: 4,
    rounding: 0,
  },
  XRL: {
    code: "XRL",
    symbol: undefined,
    name: "Rialto",
    precision: 4,
    rounding: 0,
  },
  VSL: {
    code: "VSL",
    symbol: undefined,
    name: "vSlice",
    precision: 4,
    rounding: 0,
  },
  QRL: {
    code: "QRL",
    symbol: undefined,
    name: "Quantum Resis...",
    precision: 4,
    rounding: 0,
  },
  MSP: {
    code: "MSP",
    symbol: undefined,
    name: "Mothership",
    precision: 4,
    rounding: 0,
  },
  ADT: {
    code: "ADT",
    symbol: undefined,
    name: "adToken",
    precision: 4,
    rounding: 0,
  },
  FAIR: {
    code: "FAIR",
    symbol: undefined,
    name: "FairCoin",
    precision: 4,
    rounding: 0,
  },
  RDD: {
    code: "RDD",
    symbol: undefined,
    name: "ReddCoin",
    precision: 4,
    rounding: 0,
  },
  LUN: {
    code: "LUN",
    symbol: undefined,
    name: "Lunyr",
    precision: 4,
    rounding: 0,
  },
  VIA: {
    code: "VIA",
    symbol: undefined,
    name: "Viacoin",
    precision: 4,
    rounding: 0,
  },
  VTC: {
    code: "VTC",
    symbol: undefined,
    name: "Vertcoin",
    precision: 4,
    rounding: 0,
  },
  NMC: {
    code: "NMC",
    symbol: undefined,
    name: "Namecoin",
    precision: 4,
    rounding: 0,
  },
  PST: {
    code: "PST",
    symbol: undefined,
    name: "Primas",
    precision: 4,
    rounding: 0,
  },
  EXP: {
    code: "EXP",
    symbol: undefined,
    name: "Expanse",
    precision: 4,
    rounding: 0,
  },
  DICE: {
    code: "DICE",
    symbol: undefined,
    name: "Etheroll",
    precision: 4,
    rounding: 0,
  },
  SAN: {
    code: "SAN",
    symbol: undefined,
    name: "Santiment Net...",
    precision: 4,
    rounding: 0,
  },
  TCC: {
    code: "TCC",
    symbol: undefined,
    name: "The ChampCoin",
    precision: 4,
    rounding: 0,
  },
  MYST: {
    code: "MYST",
    symbol: undefined,
    name: "Mysterium",
    precision: 4,
    rounding: 0,
  },
  UNITY: {
    code: "UNITY",
    symbol: undefined,
    name: "SuperNET",
    precision: 4,
    rounding: 0,
  },
  HMQ: {
    code: "HMQ",
    symbol: undefined,
    name: "Humaniq",
    precision: 4,
    rounding: 0,
  },
  ION: {
    code: "ION",
    symbol: undefined,
    name: "ION",
    precision: 4,
    rounding: 0,
  },
  POT: {
    code: "POT",
    symbol: undefined,
    name: "PotCoin",
    precision: 4,
    rounding: 0,
  },
  SNM: {
    code: "SNM",
    symbol: undefined,
    name: "SONM",
    precision: 4,
    rounding: 0,
  },
  TRST: {
    code: "TRST",
    symbol: undefined,
    name: "WeTrust",
    precision: 4,
    rounding: 0,
  },
  EB3: {
    code: "EB3",
    symbol: undefined,
    name: "EB3 Coin",
    precision: 4,
    rounding: 0,
  },
  CLOAK: {
    code: "CLOAK",
    symbol: undefined,
    name: "CloakCoin",
    precision: 4,
    rounding: 0,
  },
  CRW: {
    code: "CRW",
    symbol: undefined,
    name: "Crown",
    precision: 4,
    rounding: 0,
  },
  PTOY: {
    code: "PTOY",
    symbol: undefined,
    name: "Patientory",
    precision: 4,
    rounding: 0,
  },
  SAFEX: {
    code: "SAFEX",
    symbol: undefined,
    name: "Safe Exchange...",
    precision: 4,
    rounding: 0,
  },
  OAX: {
    code: "OAX",
    symbol: undefined,
    name: "OpenAnx",
    precision: 4,
    rounding: 0,
  },
  MONA: {
    code: "MONA",
    symbol: undefined,
    name: "MonaCoin",
    precision: 4,
    rounding: 0,
  },
  PLBT: {
    code: "PLBT",
    symbol: undefined,
    name: "Polybius",
    precision: 4,
    rounding: 0,
  },
  IXT: {
    code: "IXT",
    symbol: undefined,
    name: "InsureX",
    precision: 4,
    rounding: 0,
  },
  XAUR: {
    code: "XAUR",
    symbol: undefined,
    name: "Xaurum",
    precision: 4,
    rounding: 0,
  },
  LBC: {
    code: "LBC",
    symbol: undefined,
    name: "LBRY Credits",
    precision: 4,
    rounding: 0,
  },
  SPR: {
    code: "SPR",
    symbol: undefined,
    name: "SpreadCoin",
    precision: 4,
    rounding: 0,
  },
  ZEN: {
    code: "ZEN",
    symbol: undefined,
    name: "ZenCash",
    precision: 4,
    rounding: 0,
  },
  SKY: {
    code: "SKY",
    symbol: undefined,
    name: "Skycoin",
    precision: 4,
    rounding: 0,
  },
  BAY: {
    code: "BAY",
    symbol: undefined,
    name: "BitBay",
    precision: 4,
    rounding: 0,
  },
  BLK: {
    code: "BLK",
    symbol: undefined,
    name: "BlackCoin",
    precision: 4,
    rounding: 0,
  },
  PPY: {
    code: "PPY",
    symbol: undefined,
    name: "Peerplays",
    precision: 4,
    rounding: 0,
  },
  OMNI: {
    code: "OMNI",
    symbol: undefined,
    name: "Omni",
    precision: 4,
    rounding: 0,
  },
  WGR: {
    code: "WGR",
    symbol: undefined,
    name: "Wagerr",
    precision: 4,
    rounding: 0,
  },
  SHIFT: {
    code: "SHIFT",
    symbol: undefined,
    name: "Shift",
    precision: 4,
    rounding: 0,
  },
  NXC: {
    code: "NXC",
    symbol: undefined,
    name: "Nexium",
    precision: 4,
    rounding: 0,
  },
  GUP: {
    code: "GUP",
    symbol: undefined,
    name: "Matchpool",
    precision: 4,
    rounding: 0,
  },
  RADS: {
    code: "RADS",
    symbol: undefined,
    name: "Radium",
    precision: 4,
    rounding: 0,
  },
  CLAM: {
    code: "CLAM",
    symbol: undefined,
    name: "Clams",
    precision: 4,
    rounding: 0,
  },
  MUE: {
    code: "MUE",
    symbol: undefined,
    name: "MonetaryUnit",
    precision: 4,
    rounding: 0,
  },
  SOAR: {
    code: "SOAR",
    symbol: undefined,
    name: "Soarcoin",
    precision: 4,
    rounding: 0,
  },
  DTB: {
    code: "DTB",
    symbol: undefined,
    name: "Databits",
    precision: 4,
    rounding: 0,
  },
  GOLOS: {
    code: "GOLOS",
    symbol: undefined,
    name: "Golos",
    precision: 4,
    rounding: 0,
  },
  AMP: {
    code: "AMP",
    symbol: undefined,
    name: "Synereo",
    precision: 4,
    rounding: 0,
  },
  SLS: {
    code: "SLS",
    symbol: undefined,
    name: "SaluS",
    precision: 4,
    rounding: 0,
  },
  AGRS: {
    code: "AGRS",
    symbol: undefined,
    name: "Agoras Tokens",
    precision: 4,
    rounding: 0,
  },
  TIME: {
    code: "TIME",
    symbol: undefined,
    name: "Chronobank",
    precision: 4,
    rounding: 0,
  },
  XDN: {
    code: "XDN",
    symbol: undefined,
    name: "DigitalNote",
    precision: 4,
    rounding: 0,
  },
  QAU: {
    code: "QAU",
    symbol: undefined,
    name: "Quantum",
    precision: 4,
    rounding: 0,
  },
  ENRG: {
    code: "ENRG",
    symbol: undefined,
    name: "Energycoin",
    precision: 4,
    rounding: 0,
  },
  BURST: {
    code: "BURST",
    symbol: undefined,
    name: "Burst",
    precision: 4,
    rounding: 0,
  },
  XRB: {
    code: "XRB",
    symbol: undefined,
    name: "RaiBlocks",
    precision: 4,
    rounding: 0,
  },
  YBC: {
    code: "YBC",
    symbol: undefined,
    name: "YbCoin",
    precision: 4,
    rounding: 0,
  },
  SIB: {
    code: "SIB",
    symbol: undefined,
    name: "SIBCoin",
    precision: 4,
    rounding: 0,
  },
  GRC: {
    code: "GRC",
    symbol: undefined,
    name: "GridCoin",
    precision: 4,
    rounding: 0,
  },
  BCAP: {
    code: "BCAP",
    symbol: undefined,
    name: "BCAP",
    precision: 4,
    rounding: 0,
  },
  ECOB: {
    code: "ECOB",
    symbol: undefined,
    name: "Ecobit",
    precision: 4,
    rounding: 0,
  },
  NET: {
    code: "NET",
    symbol: undefined,
    name: "Nimiq",
    precision: 4,
    rounding: 0,
  },
  EBST: {
    code: "EBST",
    symbol: undefined,
    name: "eBoost",
    precision: 4,
    rounding: 0,
  },
  "888": {
    code: "888",
    symbol: undefined,
    name: "OctoCoin",
    precision: 4,
    rounding: 0,
  },
  TIX: {
    code: "TIX",
    symbol: undefined,
    name: "Blocktix",
    precision: 4,
    rounding: 0,
  },
  "020": {
    code: "020",
    symbol: undefined,
    name: "020LondonCoin",
    precision: 4,
    rounding: 0,
  },
  XBY: {
    code: "XBY",
    symbol: undefined,
    name: "XTRABYTES",
    precision: 4,
    rounding: 0,
  },
  AEON: {
    code: "AEON",
    symbol: undefined,
    name: "Aeon",
    precision: 4,
    rounding: 0,
  },
  RBY: {
    code: "RBY",
    symbol: undefined,
    name: "Rubycoin",
    precision: 4,
    rounding: 0,
  },
  NEOS: {
    code: "NEOS",
    symbol: undefined,
    name: "NeosCoin",
    precision: 4,
    rounding: 0,
  },
  FLO: {
    code: "FLO",
    symbol: undefined,
    name: "FlorinCoin",
    precision: 4,
    rounding: 0,
  },
  RISE: {
    code: "RISE",
    symbol: undefined,
    name: "Rise",
    precision: 4,
    rounding: 0,
  },
  UNO: {
    code: "UNO",
    symbol: undefined,
    name: "Unobtanium",
    precision: 4,
    rounding: 0,
  },
  WCT: {
    code: "WCT",
    symbol: undefined,
    name: "Waves Communi...",
    precision: 4,
    rounding: 0,
  },
  XSPEC: {
    code: "XSPEC",
    symbol: undefined,
    name: "Spectrecoin",
    precision: 4,
    rounding: 0,
  },
  SWT: {
    code: "SWT",
    symbol: undefined,
    name: "Swarm City",
    precision: 4,
    rounding: 0,
  },
  VOX: {
    code: "VOX",
    symbol: undefined,
    name: "Voxels",
    precision: 4,
    rounding: 0,
  },
  ECN: {
    code: "ECN",
    symbol: undefined,
    name: "E-coin",
    precision: 4,
    rounding: 0,
  },
  BET: {
    code: "BET",
    symbol: undefined,
    name: "DAO.Casino",
    precision: 4,
    rounding: 0,
  },
  OBITS: {
    code: "OBITS",
    symbol: undefined,
    name: "OBITS",
    precision: 4,
    rounding: 0,
  },
  MUSIC: {
    code: "MUSIC",
    symbol: undefined,
    name: "Musicoin",
    precision: 4,
    rounding: 0,
  },
  EAC: {
    code: "EAC",
    symbol: undefined,
    name: "EarthCoin",
    precision: 4,
    rounding: 0,
  },
  BITCNY: {
    code: "BITCNY",
    symbol: undefined,
    name: "bitCNY",
    precision: 4,
    rounding: 0,
  },
  EDR: {
    code: "EDR",
    symbol: undefined,
    name: "E-Dinar Coin",
    precision: 4,
    rounding: 0,
  },
  DMD: {
    code: "DMD",
    symbol: undefined,
    name: "Diamond",
    precision: 4,
    rounding: 0,
  },
  PLU: {
    code: "PLU",
    symbol: undefined,
    name: "Pluton",
    precision: 4,
    rounding: 0,
  },
  INCNT: {
    code: "INCNT",
    symbol: undefined,
    name: "Incent",
    precision: 4,
    rounding: 0,
  },
  BCY: {
    code: "BCY",
    symbol: undefined,
    name: "Bitcrystals",
    precision: 4,
    rounding: 0,
  },
  UNY: {
    code: "UNY",
    symbol: undefined,
    name: "Unity Ingot",
    precision: 4,
    rounding: 0,
  },
  FTC: {
    code: "FTC",
    symbol: undefined,
    name: "Feathercoin",
    precision: 4,
    rounding: 0,
  },
  LMC: {
    code: "LMC",
    symbol: undefined,
    name: "LoMoCoin",
    precision: 4,
    rounding: 0,
  },
  DENT: {
    code: "DENT",
    symbol: undefined,
    name: "Dent",
    precision: 4,
    rounding: 0,
  },
  MOON: {
    code: "MOON",
    symbol: undefined,
    name: "Mooncoin",
    precision: 4,
    rounding: 0,
  },
  GAM: {
    code: "GAM",
    symbol: undefined,
    name: "Gambit",
    precision: 4,
    rounding: 0,
  },
  EMC2: {
    code: "EMC2",
    symbol: undefined,
    name: "Einsteinium",
    precision: 4,
    rounding: 0,
  },
  VRC: {
    code: "VRC",
    symbol: undefined,
    name: "VeriCoin",
    precision: 4,
    rounding: 0,
  },
  SPHR: {
    code: "SPHR",
    symbol: undefined,
    name: "Sphere",
    precision: 4,
    rounding: 0,
  },
  ECC: {
    code: "ECC",
    symbol: undefined,
    name: "E-Currency Coin",
    precision: 4,
    rounding: 0,
  },
  ONION: {
    code: "ONION",
    symbol: undefined,
    name: "DeepOnion",
    precision: 4,
    rounding: 0,
  },
  HEAT: {
    code: "HEAT",
    symbol: undefined,
    name: "HEAT",
    precision: 4,
    rounding: 0,
  },
  XPM: {
    code: "XPM",
    symbol: undefined,
    name: "Primecoin",
    precision: 4,
    rounding: 0,
  },
  TFL: {
    code: "TFL",
    symbol: undefined,
    name: "TrueFlip",
    precision: 4,
    rounding: 0,
  },
  TOA: {
    code: "TOA",
    symbol: undefined,
    name: "ToaCoin",
    precision: 4,
    rounding: 0,
  },
  FLDC: {
    code: "FLDC",
    symbol: undefined,
    name: "FoldingCoin",
    precision: 4,
    rounding: 0,
  },
  XBC: {
    code: "XBC",
    symbol: undefined,
    name: "Bitcoin Plus",
    precision: 4,
    rounding: 0,
  },
  PUT: {
    code: "PUT",
    symbol: undefined,
    name: "PutinCoin",
    precision: 4,
    rounding: 0,
  },
  NOTE: {
    code: "NOTE",
    symbol: undefined,
    name: "DNotes",
    precision: 4,
    rounding: 0,
  },
  PEPECASH: {
    code: "PEPECASH",
    symbol: undefined,
    name: "Pepe Cash",
    precision: 4,
    rounding: 0,
  },
  GRS: {
    code: "GRS",
    symbol: undefined,
    name: "Groestlcoin",
    precision: 4,
    rounding: 0,
  },
  "300": {
    code: "300",
    symbol: undefined,
    name: "300 Token",
    precision: 4,
    rounding: 0,
  },
  EMV: {
    code: "EMV",
    symbol: undefined,
    name: "Ethereum Movi...",
    precision: 4,
    rounding: 0,
  },
  PINK: {
    code: "PINK",
    symbol: undefined,
    name: "PinkCoin",
    precision: 4,
    rounding: 0,
  },
  CRB: {
    code: "CRB",
    symbol: undefined,
    name: "Creditbit",
    precision: 4,
    rounding: 0,
  },
  WDC: {
    code: "WDC",
    symbol: undefined,
    name: "WorldCoin",
    precision: 4,
    rounding: 0,
  },
  IFC: {
    code: "IFC",
    symbol: undefined,
    name: "Infinitecoin",
    precision: 4,
    rounding: 0,
  },
  TRIG: {
    code: "TRIG",
    symbol: undefined,
    name: "Triggers",
    precision: 4,
    rounding: 0,
  },
  MYB: {
    code: "MYB",
    symbol: undefined,
    name: "MyBit Token",
    precision: 4,
    rounding: 0,
  },
  MBRS: {
    code: "MBRS",
    symbol: undefined,
    name: "Embers",
    precision: 4,
    rounding: 0,
  },
  EXCL: {
    code: "EXCL",
    symbol: undefined,
    name: "ExclusiveCoin",
    precision: 4,
    rounding: 0,
  },
  QWARK: {
    code: "QWARK",
    symbol: undefined,
    name: "Qwark",
    precision: 4,
    rounding: 0,
  },
  NDC: {
    code: "NDC",
    symbol: undefined,
    name: "NEVERDIE",
    precision: 4,
    rounding: 0,
  },
  APX: {
    code: "APX",
    symbol: undefined,
    name: "APX",
    precision: 4,
    rounding: 0,
  },
  SEQ: {
    code: "SEQ",
    symbol: undefined,
    name: "Sequence",
    precision: 4,
    rounding: 0,
  },
  SLR: {
    code: "SLR",
    symbol: undefined,
    name: "SolarCoin",
    precision: 4,
    rounding: 0,
  },
  GRE: {
    code: "GRE",
    symbol: undefined,
    name: "Greencoin",
    precision: 4,
    rounding: 0,
  },
  PZM: {
    code: "PZM",
    symbol: undefined,
    name: "PRIZM",
    precision: 4,
    rounding: 0,
  },
  PDC: {
    code: "PDC",
    symbol: undefined,
    name: "Project Decorum",
    precision: 4,
    rounding: 0,
  },
  BASH: {
    code: "BASH",
    symbol: undefined,
    name: "LuckChain",
    precision: 4,
    rounding: 0,
  },
  OCT: {
    code: "OCT",
    symbol: undefined,
    name: "OracleChain",
    precision: 4,
    rounding: 0,
  },
  SNRG: {
    code: "SNRG",
    symbol: undefined,
    name: "Synergy",
    precision: 4,
    rounding: 0,
  },
  VASH: {
    code: "VASH",
    symbol: undefined,
    name: "VPNCoin",
    precision: 4,
    rounding: 0,
  },
  BELA: {
    code: "BELA",
    symbol: undefined,
    name: "Bela",
    precision: 4,
    rounding: 0,
  },
  DBIX: {
    code: "DBIX",
    symbol: undefined,
    name: "DubaiCoin",
    precision: 4,
    rounding: 0,
  },
  PBT: {
    code: "PBT",
    symbol: undefined,
    name: "Primalbase Token",
    precision: 4,
    rounding: 0,
  },
  PASC: {
    code: "PASC",
    symbol: undefined,
    name: "Pascal Coin",
    precision: 4,
    rounding: 0,
  },
  BSD: {
    code: "BSD",
    symbol: undefined,
    name: "BitSend",
    precision: 4,
    rounding: 0,
  },
  OK: {
    code: "OK",
    symbol: undefined,
    name: "OKCash",
    precision: 4,
    rounding: 0,
  },
  ABY: {
    code: "ABY",
    symbol: undefined,
    name: "ArtByte",
    precision: 4,
    rounding: 0,
  },
  CURE: {
    code: "CURE",
    symbol: undefined,
    name: "Curecoin",
    precision: 4,
    rounding: 0,
  },
  NVC: {
    code: "NVC",
    symbol: undefined,
    name: "Novacoin",
    precision: 4,
    rounding: 0,
  },
  SNC: {
    code: "SNC",
    symbol: undefined,
    name: "SunContract",
    precision: 4,
    rounding: 0,
  },
  GCR: {
    code: "GCR",
    symbol: undefined,
    name: "Global Curren...",
    precision: 4,
    rounding: 0,
  },
  ZCL: {
    code: "ZCL",
    symbol: undefined,
    name: "ZClassic",
    precision: 4,
    rounding: 0,
  },
  XC: {
    code: "XC",
    symbol: undefined,
    name: "XCurrency",
    precision: 4,
    rounding: 0,
  },
  AUR: {
    code: "AUR",
    symbol: undefined,
    name: "Auroracoin",
    precision: 4,
    rounding: 0,
  },
  NVST: {
    code: "NVST",
    symbol: undefined,
    name: "NVO",
    precision: 4,
    rounding: 0,
  },
  COVAL: {
    code: "COVAL",
    symbol: undefined,
    name: "Circuits of V...",
    precision: 4,
    rounding: 0,
  },
  QRK: {
    code: "QRK",
    symbol: undefined,
    name: "Quark",
    precision: 4,
    rounding: 0,
  },
  BLITZ: {
    code: "BLITZ",
    symbol: undefined,
    name: "Blitzcash",
    precision: 4,
    rounding: 0,
  },
  XVC: {
    code: "XVC",
    symbol: undefined,
    name: "Vcash",
    precision: 4,
    rounding: 0,
  },
  "611": {
    code: "611",
    symbol: undefined,
    name: "SixEleven",
    precision: 4,
    rounding: 0,
  },
  SIGT: {
    code: "SIGT",
    symbol: undefined,
    name: "Signatum",
    precision: 4,
    rounding: 0,
  },
  BITB: {
    code: "BITB",
    symbol: undefined,
    name: "BitBean",
    precision: 4,
    rounding: 0,
  },
  ZRC: {
    code: "ZRC",
    symbol: undefined,
    name: "ZrCoin",
    precision: 4,
    rounding: 0,
  },
  EMB: {
    code: "EMB",
    symbol: undefined,
    name: "EmberCoin",
    precision: 4,
    rounding: 0,
  },
  SWIFT: {
    code: "SWIFT",
    symbol: undefined,
    name: "Bitswift",
    precision: 4,
    rounding: 0,
  },
  ICOO: {
    code: "ICOO",
    symbol: undefined,
    name: "ICO OpenLedger",
    precision: 4,
    rounding: 0,
  },
  DAR: {
    code: "DAR",
    symbol: undefined,
    name: "Darcrus",
    precision: 4,
    rounding: 0,
  },
  MAX: {
    code: "MAX",
    symbol: undefined,
    name: "MaxCoin",
    precision: 4,
    rounding: 0,
  },
  MEC: {
    code: "MEC",
    symbol: undefined,
    name: "Megacoin",
    precision: 4,
    rounding: 0,
  },
  DAXX: {
    code: "DAXX",
    symbol: undefined,
    name: "DaxxCoin",
    precision: 4,
    rounding: 0,
  },
  CVCOIN: {
    code: "CVCOIN",
    symbol: undefined,
    name: "CVCoin",
    precision: 4,
    rounding: 0,
  },
  GLD: {
    code: "GLD",
    symbol: undefined,
    name: "GoldCoin",
    precision: 4,
    rounding: 0,
  },
  DYN: {
    code: "DYN",
    symbol: undefined,
    name: "Dynamic",
    precision: 4,
    rounding: 0,
  },
  XST: {
    code: "XST",
    symbol: undefined,
    name: "Stealthcoin",
    precision: 4,
    rounding: 0,
  },
  GEO: {
    code: "GEO",
    symbol: undefined,
    name: "GeoCoin",
    precision: 4,
    rounding: 0,
  },
  ERC: {
    code: "ERC",
    symbol: undefined,
    name: "EuropeCoin",
    precision: 4,
    rounding: 0,
  },
  ATCC: {
    code: "ATCC",
    symbol: undefined,
    name: "ATC Coin",
    precision: 4,
    rounding: 0,
  },
  ETT: {
    code: "ETT",
    symbol: undefined,
    name: "EncryptoTel",
    precision: 4,
    rounding: 0,
  },
  HTML5: {
    code: "HTML5",
    symbol: undefined,
    name: "HTMLCOIN",
    precision: 4,
    rounding: 0,
  },
  "420G": {
    code: "420G",
    symbol: undefined,
    name: "GanjaCoin",
    precision: 4,
    rounding: 0,
  },
  CADASTRAL: {
    code: "CADASTRAL",
    symbol: undefined,
    name: "Bitland",
    precision: 4,
    rounding: 0,
  },
  WBB: {
    code: "WBB",
    symbol: undefined,
    name: "Wild Beast Block",
    precision: 4,
    rounding: 0,
  },
  MNE: {
    code: "MNE",
    symbol: undefined,
    name: "Minereum",
    precision: 4,
    rounding: 0,
  },
  RAIN: {
    code: "RAIN",
    symbol: undefined,
    name: "Condensate",
    precision: 4,
    rounding: 0,
  },
  KORE: {
    code: "KORE",
    symbol: undefined,
    name: "KoreCoin",
    precision: 4,
    rounding: 0,
  },
  ZET: {
    code: "ZET",
    symbol: undefined,
    name: "Zetacoin",
    precision: 4,
    rounding: 0,
  },
  ESP: {
    code: "ESP",
    symbol: undefined,
    name: "Espers",
    precision: 4,
    rounding: 0,
  },
  XCN: {
    code: "XCN",
    symbol: undefined,
    name: "Cryptonite",
    precision: 4,
    rounding: 0,
  },
  SMART: {
    code: "SMART",
    symbol: undefined,
    name: "SmartCash",
    precision: 4,
    rounding: 0,
  },
  ZENI: {
    code: "ZENI",
    symbol: undefined,
    name: "Zennies",
    precision: 4,
    rounding: 0,
  },
  BITUSD: {
    code: "BITUSD",
    symbol: undefined,
    name: "bitUSD",
    precision: 4,
    rounding: 0,
  },
  DIME: {
    code: "DIME",
    symbol: undefined,
    name: "Dimecoin",
    precision: 4,
    rounding: 0,
  },
  BTM2: {
    code: "BTM2",
    symbol: undefined,
    name: "Bitmark",
    precision: 4,
    rounding: 0,
  },
  BTA: {
    code: "BTA",
    symbol: undefined,
    name: "Bata",
    precision: 4,
    rounding: 0,
  },
  BRX: {
    code: "BRX",
    symbol: undefined,
    name: "Breakout Stake",
    precision: 4,
    rounding: 0,
  },
  BPC: {
    code: "BPC",
    symbol: undefined,
    name: "Bitpark Coin",
    precision: 4,
    rounding: 0,
  },
  RIC: {
    code: "RIC",
    symbol: undefined,
    name: "Riecoin",
    precision: 4,
    rounding: 0,
  },
  LGD: {
    code: "LGD",
    symbol: undefined,
    name: "Legends Room",
    precision: 4,
    rounding: 0,
  },
  XMY: {
    code: "XMY",
    symbol: undefined,
    name: "Myriad",
    precision: 4,
    rounding: 0,
  },
  EQT: {
    code: "EQT",
    symbol: undefined,
    name: "EquiTrader",
    precision: 4,
    rounding: 0,
  },
  SBD: {
    code: "SBD",
    symbol: undefined,
    name: "Steem Dollars",
    precision: 4,
    rounding: 0,
  },
  MINT: {
    code: "MINT",
    symbol: undefined,
    name: "Mintcoin",
    precision: 4,
    rounding: 0,
  },
  CHC: {
    code: "CHC",
    symbol: undefined,
    name: "ChainCoin",
    precision: 4,
    rounding: 0,
  },
  FYN: {
    code: "FYN",
    symbol: undefined,
    name: "FundYourselfNow",
    precision: 4,
    rounding: 0,
  },
  VSM: {
    code: "VSM",
    symbol: undefined,
    name: "VOISE",
    precision: 4,
    rounding: 0,
  },
  LNK: {
    code: "LNK",
    symbol: undefined,
    name: "Link Platform",
    precision: 4,
    rounding: 0,
  },
  ZCC: {
    code: "ZCC",
    symbol: undefined,
    name: "ZcCoin",
    precision: 4,
    rounding: 0,
  },
  TIPS: {
    code: "TIPS",
    symbol: undefined,
    name: "FedoraCoin",
    precision: 4,
    rounding: 0,
  },
  DOPE: {
    code: "DOPE",
    symbol: undefined,
    name: "DopeCoin",
    precision: 4,
    rounding: 0,
  },
  MXT: {
    code: "MXT",
    symbol: undefined,
    name: "MarteXcoin",
    precision: 4,
    rounding: 0,
  },
  BRK: {
    code: "BRK",
    symbol: undefined,
    name: "Breakout",
    precision: 4,
    rounding: 0,
  },
  AC: {
    code: "AC",
    symbol: undefined,
    name: "AsiaCoin",
    precision: 4,
    rounding: 0,
  },
  VRM: {
    code: "VRM",
    symbol: undefined,
    name: "VeriumReserve",
    precision: 4,
    rounding: 0,
  },
  TX: {
    code: "TX",
    symbol: undefined,
    name: "TransferCoin",
    precision: 4,
    rounding: 0,
  },
  CMP: {
    code: "CMP",
    symbol: undefined,
    name: "Compcoin",
    precision: 4,
    rounding: 0,
  },
  SYNX: {
    code: "SYNX",
    symbol: undefined,
    name: "Syndicate",
    precision: 4,
    rounding: 0,
  },
  DCN: {
    code: "DCN",
    symbol: undefined,
    name: "Dentacoin",
    precision: 4,
    rounding: 0,
  },
  NAUT: {
    code: "NAUT",
    symbol: undefined,
    name: "NautilusCoin",
    precision: 4,
    rounding: 0,
  },
  STA: {
    code: "STA",
    symbol: undefined,
    name: "Starta",
    precision: 4,
    rounding: 0,
  },
  MEME: {
    code: "MEME",
    symbol: undefined,
    name: "Memetic",
    precision: 4,
    rounding: 0,
  },
  CRAVE: {
    code: "CRAVE",
    symbol: undefined,
    name: "Crave",
    precision: 4,
    rounding: 0,
  },
  "2GIVE": {
    code: "2GIVE",
    symbol: undefined,
    name: "2GIVE",
    precision: 4,
    rounding: 0,
  },
  NTRN: {
    code: "NTRN",
    symbol: undefined,
    name: "Neutron",
    precision: 4,
    rounding: 0,
  },
  CV2: {
    code: "CV2",
    symbol: undefined,
    name: "Colossuscoin V2",
    precision: 4,
    rounding: 0,
  },
  PTC: {
    code: "PTC",
    symbol: undefined,
    name: "Pesetacoin",
    precision: 4,
    rounding: 0,
  },
  SKIN: {
    code: "SKIN",
    symbol: undefined,
    name: "SkinCoin",
    precision: 4,
    rounding: 0,
  },
  EGC: {
    code: "EGC",
    symbol: undefined,
    name: "EverGreenCoin",
    precision: 4,
    rounding: 0,
  },
  ADZ: {
    code: "ADZ",
    symbol: undefined,
    name: "Adzcoin",
    precision: 4,
    rounding: 0,
  },
  ATMS: {
    code: "ATMS",
    symbol: undefined,
    name: "Atmos",
    precision: 4,
    rounding: 0,
  },
  INSN: {
    code: "INSN",
    symbol: undefined,
    name: "InsaneCoin",
    precision: 4,
    rounding: 0,
  },
  ZEIT: {
    code: "ZEIT",
    symbol: undefined,
    name: "Zeitcoin",
    precision: 4,
    rounding: 0,
  },
  PIE: {
    code: "PIE",
    symbol: undefined,
    name: "PIECoin",
    precision: 4,
    rounding: 0,
  },
  HUC: {
    code: "HUC",
    symbol: undefined,
    name: "HunterCoin",
    precision: 4,
    rounding: 0,
  },
  XBB: {
    code: "XBB",
    symbol: undefined,
    name: "Boolberry",
    precision: 4,
    rounding: 0,
  },
  TKS: {
    code: "TKS",
    symbol: undefined,
    name: "Tokes",
    precision: 4,
    rounding: 0,
  },
  CANN: {
    code: "CANN",
    symbol: undefined,
    name: "CannabisCoin",
    precision: 4,
    rounding: 0,
  },
  COE: {
    code: "COE",
    symbol: undefined,
    name: "CoEval",
    precision: 4,
    rounding: 0,
  },
  CREA: {
    code: "CREA",
    symbol: undefined,
    name: "Creativecoin",
    precision: 4,
    rounding: 0,
  },
  PKB: {
    code: "PKB",
    symbol: undefined,
    name: "ParkByte",
    precision: 4,
    rounding: 0,
  },
  THC: {
    code: "THC",
    symbol: undefined,
    name: "HempCoin",
    precision: 4,
    rounding: 0,
  },
  VTR: {
    code: "VTR",
    symbol: undefined,
    name: "vTorrent",
    precision: 4,
    rounding: 0,
  },
  POSW: {
    code: "POSW",
    symbol: undefined,
    name: "PoSW Coin",
    precision: 4,
    rounding: 0,
  },
  INPAY: {
    code: "INPAY",
    symbol: undefined,
    name: "InPay",
    precision: 4,
    rounding: 0,
  },
  XWC: {
    code: "XWC",
    symbol: undefined,
    name: "WhiteCoin",
    precision: 4,
    rounding: 0,
  },
  INSANE: {
    code: "INSANE",
    symbol: undefined,
    name: "InsaneCoin",
    precision: 4,
    rounding: 0,
  },
  TRC: {
    code: "TRC",
    symbol: undefined,
    name: "Terracoin",
    precision: 4,
    rounding: 0,
  },
  TAG: {
    code: "TAG",
    symbol: undefined,
    name: "TagCoin",
    precision: 4,
    rounding: 0,
  },
  ALT: {
    code: "ALT",
    symbol: undefined,
    name: "Altcoin",
    precision: 4,
    rounding: 0,
  },
  LINDA: {
    code: "LINDA",
    symbol: undefined,
    name: "Linda",
    precision: 4,
    rounding: 0,
  },
  START: {
    code: "START",
    symbol: undefined,
    name: "Startcoin",
    precision: 4,
    rounding: 0,
  },
  ADST: {
    code: "ADST",
    symbol: undefined,
    name: "AdShares",
    precision: 4,
    rounding: 0,
  },
  DOT: {
    code: "DOT",
    symbol: undefined,
    name: "Dotcoin",
    precision: 4,
    rounding: 0,
  },
  HUSH: {
    code: "HUSH",
    symbol: undefined,
    name: "Hush",
    precision: 4,
    rounding: 0,
  },
  CAGE: {
    code: "CAGE",
    symbol: undefined,
    name: "CageCoin",
    precision: 4,
    rounding: 0,
  },
  EFL: {
    code: "EFL",
    symbol: undefined,
    name: "e-Gulden",
    precision: 4,
    rounding: 0,
  },
  VISIO: {
    code: "VISIO",
    symbol: undefined,
    name: "Visio",
    precision: 4,
    rounding: 0,
  },
  BLOCKPAY: {
    code: "BLOCKPAY",
    symbol: undefined,
    name: "BlockPay",
    precision: 4,
    rounding: 0,
  },
  PING: {
    code: "PING",
    symbol: undefined,
    name: "CryptoPing",
    precision: 4,
    rounding: 0,
  },
  JNS: {
    code: "JNS",
    symbol: undefined,
    name: "Janus",
    precision: 4,
    rounding: 0,
  },
  CCM100: {
    code: "CCM100",
    symbol: undefined,
    name: "CCMiner",
    precision: 4,
    rounding: 0,
  },
  GCN: {
    code: "GCN",
    symbol: undefined,
    name: "GCoin",
    precision: 4,
    rounding: 0,
  },
  SMLY: {
    code: "SMLY",
    symbol: undefined,
    name: "SmileyCoin",
    precision: 4,
    rounding: 0,
  },
  XMG: {
    code: "XMG",
    symbol: undefined,
    name: "Magi",
    precision: 4,
    rounding: 0,
  },
  TRUST: {
    code: "TRUST",
    symbol: undefined,
    name: "TrustPlus",
    precision: 4,
    rounding: 0,
  },
  FNC: {
    code: "FNC",
    symbol: undefined,
    name: "FinCoin",
    precision: 4,
    rounding: 0,
  },
  IXC: {
    code: "IXC",
    symbol: undefined,
    name: "Ixcoin",
    precision: 4,
    rounding: 0,
  },
  CNT: {
    code: "CNT",
    symbol: undefined,
    name: "Centurion",
    precision: 4,
    rounding: 0,
  },
  CCRB: {
    code: "CCRB",
    symbol: undefined,
    name: "CryptoCarbon",
    precision: 4,
    rounding: 0,
  },
  MER: {
    code: "MER",
    symbol: undefined,
    name: "Mercury",
    precision: 4,
    rounding: 0,
  },
  SPRTS: {
    code: "SPRTS",
    symbol: undefined,
    name: "Sprouts",
    precision: 4,
    rounding: 0,
  },
  PEPE: {
    code: "PEPE",
    symbol: undefined,
    name: "PepeCoin",
    precision: 4,
    rounding: 0,
  },
  BTX2: {
    code: "BTX2",
    symbol: undefined,
    name: "Bitcore",
    precision: 4,
    rounding: 0,
  },
  HYP: {
    code: "HYP",
    symbol: undefined,
    name: "HyperStake",
    precision: 4,
    rounding: 0,
  },
  ENT: {
    code: "ENT",
    symbol: undefined,
    name: "Eternity",
    precision: 4,
    rounding: 0,
  },
  XTO: {
    code: "XTO",
    symbol: undefined,
    name: "Tao",
    precision: 4,
    rounding: 0,
  },
  FST: {
    code: "FST",
    symbol: undefined,
    name: "Fastcoin",
    precision: 4,
    rounding: 0,
  },
  RUSTBITS: {
    code: "RUSTBITS",
    symbol: undefined,
    name: "Rustbits",
    precision: 4,
    rounding: 0,
  },
  MALC: {
    code: "MALC",
    symbol: undefined,
    name: "Malcoin",
    precision: 4,
    rounding: 0,
  },
  DRACO: {
    code: "DRACO",
    symbol: undefined,
    name: "DT Token",
    precision: 4,
    rounding: 0,
  },
  YASH: {
    code: "YASH",
    symbol: undefined,
    name: "YashCoin",
    precision: 4,
    rounding: 0,
  },
  ADL: {
    code: "ADL",
    symbol: undefined,
    name: "Adelphoi",
    precision: 4,
    rounding: 0,
  },
  RIYA: {
    code: "RIYA",
    symbol: undefined,
    name: "Etheriya",
    precision: 4,
    rounding: 0,
  },
  ADC: {
    code: "ADC",
    symbol: undefined,
    name: "AudioCoin",
    precision: 4,
    rounding: 0,
  },
  BLU: {
    code: "BLU",
    symbol: undefined,
    name: "BlueCoin",
    precision: 4,
    rounding: 0,
  },
  MBI: {
    code: "MBI",
    symbol: undefined,
    name: "Monster Byte",
    precision: 4,
    rounding: 0,
  },
  LDOGE: {
    code: "LDOGE",
    symbol: undefined,
    name: "LiteDoge",
    precision: 4,
    rounding: 0,
  },
  CRM: {
    code: "CRM",
    symbol: undefined,
    name: "Cream",
    precision: 4,
    rounding: 0,
  },
  SXC: {
    code: "SXC",
    symbol: undefined,
    name: "Sexcoin",
    precision: 4,
    rounding: 0,
  },
  PND: {
    code: "PND",
    symbol: undefined,
    name: "Pandacoin",
    precision: 4,
    rounding: 0,
  },
  HNC: {
    code: "HNC",
    symbol: undefined,
    name: "Helleniccoin",
    precision: 4,
    rounding: 0,
  },
  LTBC: {
    code: "LTBC",
    symbol: undefined,
    name: "LTBcoin",
    precision: 4,
    rounding: 0,
  },
  NKA: {
    code: "NKA",
    symbol: undefined,
    name: "IncaKoin",
    precision: 4,
    rounding: 0,
  },
  XP: {
    code: "XP",
    symbol: undefined,
    name: "XP",
    precision: 4,
    rounding: 0,
  },
  TIX2: {
    code: "TIX2",
    symbol: undefined,
    name: "Tickets",
    precision: 4,
    rounding: 0,
  },
  CSC: {
    code: "CSC",
    symbol: undefined,
    name: "CasinoCoin",
    precision: 4,
    rounding: 0,
  },
  RNS: {
    code: "RNS",
    symbol: undefined,
    name: "Renos",
    precision: 4,
    rounding: 0,
  },
  FIMK: {
    code: "FIMK",
    symbol: undefined,
    name: "FIMKrypto",
    precision: 4,
    rounding: 0,
  },
  BYC: {
    code: "BYC",
    symbol: undefined,
    name: "Bytecent",
    precision: 4,
    rounding: 0,
  },
  CBX: {
    code: "CBX",
    symbol: undefined,
    name: "Crypto Bullion",
    precision: 4,
    rounding: 0,
  },
  XBTC21: {
    code: "XBTC21",
    symbol: undefined,
    name: "Bitcoin 21",
    precision: 4,
    rounding: 0,
  },
  UFO: {
    code: "UFO",
    symbol: undefined,
    name: "UFO Coin",
    precision: 4,
    rounding: 0,
  },
  LOG: {
    code: "LOG",
    symbol: undefined,
    name: "Woodcoin",
    precision: 4,
    rounding: 0,
  },
  FUCK: {
    code: "FUCK",
    symbol: undefined,
    name: "FuckToken",
    precision: 4,
    rounding: 0,
  },
  CPC: {
    code: "CPC",
    symbol: undefined,
    name: "Capricoin",
    precision: 4,
    rounding: 0,
  },
  INFX: {
    code: "INFX",
    symbol: undefined,
    name: "Influxcoin",
    precision: 4,
    rounding: 0,
  },
  UIS: {
    code: "UIS",
    symbol: undefined,
    name: "Unitus",
    precision: 4,
    rounding: 0,
  },
  NETKO: {
    code: "NETKO",
    symbol: undefined,
    name: "Netko",
    precision: 4,
    rounding: 0,
  },
  BAS: {
    code: "BAS",
    symbol: undefined,
    name: "BitAsean",
    precision: 4,
    rounding: 0,
  },
  XTC: {
    code: "XTC",
    symbol: undefined,
    name: "TileCoin",
    precision: 4,
    rounding: 0,
  },
  CASINO: {
    code: "CASINO",
    symbol: undefined,
    name: "Casino",
    precision: 4,
    rounding: 0,
  },
  HPC: {
    code: "HPC",
    symbol: undefined,
    name: "Happycoin",
    precision: 4,
    rounding: 0,
  },
  SDC: {
    code: "SDC",
    symbol: undefined,
    name: "ShadowCash",
    precision: 4,
    rounding: 0,
  },
  BRO: {
    code: "BRO",
    symbol: undefined,
    name: "Bitradio",
    precision: 4,
    rounding: 0,
  },
  E4ROW: {
    code: "E4ROW",
    symbol: undefined,
    name: "E4ROW",
    precision: 4,
    rounding: 0,
  },
  FCN: {
    code: "FCN",
    symbol: undefined,
    name: "Fantomcoin",
    precision: 4,
    rounding: 0,
  },
  MRT: {
    code: "MRT",
    symbol: undefined,
    name: "Miners' Rewar...",
    precision: 4,
    rounding: 0,
  },
  OTX: {
    code: "OTX",
    symbol: undefined,
    name: "Octanox",
    precision: 4,
    rounding: 0,
  },
  MOIN: {
    code: "MOIN",
    symbol: undefined,
    name: "Moin",
    precision: 4,
    rounding: 0,
  },
  GLC: {
    code: "GLC",
    symbol: undefined,
    name: "GlobalCoin",
    precision: 4,
    rounding: 0,
  },
  ADK: {
    code: "ADK",
    symbol: undefined,
    name: "Aidos Kuneen",
    precision: 4,
    rounding: 0,
  },
  HKG: {
    code: "HKG",
    symbol: undefined,
    name: "Hacker Gold",
    precision: 4,
    rounding: 0,
  },
  ICE: {
    code: "ICE",
    symbol: undefined,
    name: "iDice",
    precision: 4,
    rounding: 0,
  },
  WGO: {
    code: "WGO",
    symbol: undefined,
    name: "WavesGo",
    precision: 4,
    rounding: 0,
  },
  PROC: {
    code: "PROC",
    symbol: undefined,
    name: "ProCurrency",
    precision: 4,
    rounding: 0,
  },
  FUNC: {
    code: "FUNC",
    symbol: undefined,
    name: "FUNCoin",
    precision: 4,
    rounding: 0,
  },
  HERO: {
    code: "HERO",
    symbol: undefined,
    name: "Sovereign Hero",
    precision: 4,
    rounding: 0,
  },
  LINX: {
    code: "LINX",
    symbol: undefined,
    name: "Linx",
    precision: 4,
    rounding: 0,
  },
  RBX: {
    code: "RBX",
    symbol: undefined,
    name: "Ripto Bux",
    precision: 4,
    rounding: 0,
  },
  BTD: {
    code: "BTD",
    symbol: undefined,
    name: "Bitcloud",
    precision: 4,
    rounding: 0,
  },
  ORB: {
    code: "ORB",
    symbol: undefined,
    name: "Orbitcoin",
    precision: 4,
    rounding: 0,
  },
  UNB: {
    code: "UNB",
    symbol: undefined,
    name: "UnbreakableCoin",
    precision: 4,
    rounding: 0,
  },
  CARBON: {
    code: "CARBON",
    symbol: undefined,
    name: "Carboncoin",
    precision: 4,
    rounding: 0,
  },
  TES: {
    code: "TES",
    symbol: undefined,
    name: "TeslaCoin",
    precision: 4,
    rounding: 0,
  },
  NET2: {
    code: "NET2",
    symbol: undefined,
    name: "NetCoin",
    precision: 4,
    rounding: 0,
  },
  ECA: {
    code: "ECA",
    symbol: undefined,
    name: "Electra",
    precision: 4,
    rounding: 0,
  },
  GOOD: {
    code: "GOOD",
    symbol: undefined,
    name: "Good Karma",
    precision: 4,
    rounding: 0,
  },
  CDN: {
    code: "CDN",
    symbol: undefined,
    name: "Canada eCoin",
    precision: 4,
    rounding: 0,
  },
  TALK: {
    code: "TALK",
    symbol: undefined,
    name: "BTCtalkcoin",
    precision: 4,
    rounding: 0,
  },
  XVP: {
    code: "XVP",
    symbol: undefined,
    name: "Virtacoinplus",
    precision: 4,
    rounding: 0,
  },
  BITZ: {
    code: "BITZ",
    symbol: undefined,
    name: "Bitz",
    precision: 4,
    rounding: 0,
  },
  DVC: {
    code: "DVC",
    symbol: undefined,
    name: "Devcoin",
    precision: 4,
    rounding: 0,
  },
  DCY: {
    code: "DCY",
    symbol: undefined,
    name: "Dinastycoin",
    precision: 4,
    rounding: 0,
  },
  USC: {
    code: "USC",
    symbol: undefined,
    name: "Ultimate Secu...",
    precision: 4,
    rounding: 0,
  },
  VUC: {
    code: "VUC",
    symbol: undefined,
    name: "Virta Unique ...",
    precision: 4,
    rounding: 0,
  },
  METAL: {
    code: "METAL",
    symbol: undefined,
    name: "MetalCoin",
    precision: 4,
    rounding: 0,
  },
  SHDW: {
    code: "SHDW",
    symbol: undefined,
    name: "Shadow Token",
    precision: 4,
    rounding: 0,
  },
  XVS: {
    code: "XVS",
    symbol: undefined,
    name: "Vsync",
    precision: 4,
    rounding: 0,
  },
  XCXT: {
    code: "XCXT",
    symbol: undefined,
    name: "CoinonatX",
    precision: 4,
    rounding: 0,
  },
  FJC: {
    code: "FJC",
    symbol: undefined,
    name: "FujiCoin",
    precision: 4,
    rounding: 0,
  },
  IFLT: {
    code: "IFLT",
    symbol: undefined,
    name: "InflationCoin",
    precision: 4,
    rounding: 0,
  },
  POST: {
    code: "POST",
    symbol: undefined,
    name: "PostCoin",
    precision: 4,
    rounding: 0,
  },
  USNBT: {
    code: "USNBT",
    symbol: undefined,
    name: "NuBits",
    precision: 4,
    rounding: 0,
  },
  PXC: {
    code: "PXC",
    symbol: undefined,
    name: "Phoenixcoin",
    precision: 4,
    rounding: 0,
  },
  NOBL: {
    code: "NOBL",
    symbol: undefined,
    name: "NobleCoin",
    precision: 4,
    rounding: 0,
  },
  CFT: {
    code: "CFT",
    symbol: undefined,
    name: "CryptoForecast",
    precision: 4,
    rounding: 0,
  },
  KEK: {
    code: "KEK",
    symbol: undefined,
    name: "KekCoin",
    precision: 4,
    rounding: 0,
  },
  HTC: {
    code: "HTC",
    symbol: undefined,
    name: "HitCoin",
    precision: 4,
    rounding: 0,
  },
  ITI: {
    code: "ITI",
    symbol: undefined,
    name: "iTicoin",
    precision: 4,
    rounding: 0,
  },
  I0C: {
    code: "I0C",
    symbol: undefined,
    name: "I0Coin",
    precision: 4,
    rounding: 0,
  },
  BTSR: {
    code: "BTSR",
    symbol: undefined,
    name: "BTSR",
    precision: 4,
    rounding: 0,
  },
  KRB: {
    code: "KRB",
    symbol: undefined,
    name: "Karbowanec",
    precision: 4,
    rounding: 0,
  },
  KOBO: {
    code: "KOBO",
    symbol: undefined,
    name: "Kobocoin",
    precision: 4,
    rounding: 0,
  },
  EL: {
    code: "EL",
    symbol: undefined,
    name: "Elcoin",
    precision: 4,
    rounding: 0,
  },
  PAK: {
    code: "PAK",
    symbol: undefined,
    name: "Pakcoin",
    precision: 4,
    rounding: 0,
  },
  BTX: {
    code: "BTX",
    symbol: undefined,
    name: "BitcoinTX",
    precision: 4,
    rounding: 0,
  },
  DNR: {
    code: "DNR",
    symbol: undefined,
    name: "Denarius",
    precision: 4,
    rounding: 0,
  },
  UNIFY: {
    code: "UNIFY",
    symbol: undefined,
    name: "Unify",
    precision: 4,
    rounding: 0,
  },
  DP: {
    code: "DP",
    symbol: undefined,
    name: "DigitalPrice",
    precision: 4,
    rounding: 0,
  },
  BRIT: {
    code: "BRIT",
    symbol: undefined,
    name: "BritCoin",
    precision: 4,
    rounding: 0,
  },
  ZOI: {
    code: "ZOI",
    symbol: undefined,
    name: "Zoin",
    precision: 4,
    rounding: 0,
  },
  NEWB: {
    code: "NEWB",
    symbol: undefined,
    name: "Newbium",
    precision: 4,
    rounding: 0,
  },
  BUN: {
    code: "BUN",
    symbol: undefined,
    name: "BunnyCoin",
    precision: 4,
    rounding: 0,
  },
  RBIES: {
    code: "RBIES",
    symbol: undefined,
    name: "Rubies",
    precision: 4,
    rounding: 0,
  },
  RLT: {
    code: "RLT",
    symbol: undefined,
    name: "RouletteToken",
    precision: 4,
    rounding: 0,
  },
  STS: {
    code: "STS",
    symbol: undefined,
    name: "Stress",
    precision: 4,
    rounding: 0,
  },
  "8BIT": {
    code: "8BIT",
    symbol: undefined,
    name: "8Bit",
    precision: 4,
    rounding: 0,
  },
  CMPCO: {
    code: "CMPCO",
    symbol: undefined,
    name: "CampusCoin",
    precision: 4,
    rounding: 0,
  },
  TRUMP: {
    code: "TRUMP",
    symbol: undefined,
    name: "TrumpCoin",
    precision: 4,
    rounding: 0,
  },
  HBN: {
    code: "HBN",
    symbol: undefined,
    name: "HoboNickels",
    precision: 4,
    rounding: 0,
  },
  CACH: {
    code: "CACH",
    symbol: undefined,
    name: "CacheCoin",
    precision: 4,
    rounding: 0,
  },
  ANC: {
    code: "ANC",
    symbol: undefined,
    name: "Anoncoin",
    precision: 4,
    rounding: 0,
  },
  UTC: {
    code: "UTC",
    symbol: undefined,
    name: "UltraCoin",
    precision: 4,
    rounding: 0,
  },
  DEM: {
    code: "DEM",
    symbol: undefined,
    name: "Deutsche eMark",
    precision: 4,
    rounding: 0,
  },
  ATOM: {
    code: "ATOM",
    symbol: undefined,
    name: "Atomic Coin",
    precision: 4,
    rounding: 0,
  },
  MAC: {
    code: "MAC",
    symbol: undefined,
    name: "Machinecoin",
    precision: 4,
    rounding: 0,
  },
  HODL: {
    code: "HODL",
    symbol: undefined,
    name: "HOdlcoin",
    precision: 4,
    rounding: 0,
  },
  TROLL: {
    code: "TROLL",
    symbol: undefined,
    name: "Trollcoin",
    precision: 4,
    rounding: 0,
  },
  ZUR: {
    code: "ZUR",
    symbol: undefined,
    name: "Zurcoin",
    precision: 4,
    rounding: 0,
  },
  PIGGY: {
    code: "PIGGY",
    symbol: undefined,
    name: "Piggycoin",
    precision: 4,
    rounding: 0,
  },
  CON: {
    code: "CON",
    symbol: undefined,
    name: "PayCon",
    precision: 4,
    rounding: 0,
  },
  MZC: {
    code: "MZC",
    symbol: undefined,
    name: "MazaCoin",
    precision: 4,
    rounding: 0,
  },
  SUMO: {
    code: "SUMO",
    symbol: undefined,
    name: "Sumokoin",
    precision: 4,
    rounding: 0,
  },
  XPY: {
    code: "XPY",
    symbol: undefined,
    name: "PayCoin",
    precision: 4,
    rounding: 0,
  },
  DAS: {
    code: "DAS",
    symbol: undefined,
    name: "DAS",
    precision: 4,
    rounding: 0,
  },
  RC: {
    code: "RC",
    symbol: undefined,
    name: "RussiaCoin",
    precision: 4,
    rounding: 0,
  },
  V: {
    code: "V",
    symbol: undefined,
    name: "Version",
    precision: 4,
    rounding: 0,
  },
  VLT: {
    code: "VLT",
    symbol: undefined,
    name: "Veltor",
    precision: 4,
    rounding: 0,
  },
  CNC: {
    code: "CNC",
    symbol: undefined,
    name: "CHNCoin",
    precision: 4,
    rounding: 0,
  },
  BTB: {
    code: "BTB",
    symbol: undefined,
    name: "BitBar",
    precision: 4,
    rounding: 0,
  },
  GAIA: {
    code: "GAIA",
    symbol: undefined,
    name: "GAIA",
    precision: 4,
    rounding: 0,
  },
  TTC: {
    code: "TTC",
    symbol: undefined,
    name: "TittieCoin",
    precision: 4,
    rounding: 0,
  },
  FLY: {
    code: "FLY",
    symbol: undefined,
    name: "Flycoin",
    precision: 4,
    rounding: 0,
  },
  Q2C: {
    code: "Q2C",
    symbol: undefined,
    name: "QubitCoin",
    precision: 4,
    rounding: 0,
  },
  CCN: {
    code: "CCN",
    symbol: undefined,
    name: "Cannacoin",
    precision: 4,
    rounding: 0,
  },
  ZER: {
    code: "ZER",
    symbol: undefined,
    name: "Zero",
    precision: 4,
    rounding: 0,
  },
  SMC: {
    code: "SMC",
    symbol: undefined,
    name: "SmartCoin",
    precision: 4,
    rounding: 0,
  },
  TRI: {
    code: "TRI",
    symbol: undefined,
    name: "Triangles",
    precision: 4,
    rounding: 0,
  },
  TRK: {
    code: "TRK",
    symbol: undefined,
    name: "Truckcoin",
    precision: 4,
    rounding: 0,
  },
  BUCKS: {
    code: "BUCKS",
    symbol: undefined,
    name: "SwagBucks",
    precision: 4,
    rounding: 0,
  },
  OHM: {
    code: "OHM",
    symbol: undefined,
    name: "OHM Wallet",
    precision: 4,
    rounding: 0,
  },
  BITS: {
    code: "BITS",
    symbol: undefined,
    name: "Bitstar",
    precision: 4,
    rounding: 0,
  },
  FXE: {
    code: "FXE",
    symbol: undefined,
    name: "FuturXe",
    precision: 4,
    rounding: 0,
  },
  AU: {
    code: "AU",
    symbol: undefined,
    name: "AurumCoin",
    precision: 4,
    rounding: 0,
  },
  SLM: {
    code: "SLM",
    symbol: undefined,
    name: "Slimcoin",
    precision: 4,
    rounding: 0,
  },
  NYC: {
    code: "NYC",
    symbol: undefined,
    name: "NewYorkCoin",
    precision: 4,
    rounding: 0,
  },
  BXT: {
    code: "BXT",
    symbol: undefined,
    name: "BitTokens",
    precision: 4,
    rounding: 0,
  },
  FC2: {
    code: "FC2",
    symbol: undefined,
    name: "FuelCoin",
    precision: 4,
    rounding: 0,
  },
  TIT: {
    code: "TIT",
    symbol: undefined,
    name: "Titcoin",
    precision: 4,
    rounding: 0,
  },
  LOT: {
    code: "LOT",
    symbol: undefined,
    name: "LottoCoin",
    precision: 4,
    rounding: 0,
  },
  YOC: {
    code: "YOC",
    symbol: undefined,
    name: "Yocoin",
    precision: 4,
    rounding: 0,
  },
  SUPER: {
    code: "SUPER",
    symbol: undefined,
    name: "SuperCoin",
    precision: 4,
    rounding: 0,
  },
  OS76: {
    code: "OS76",
    symbol: undefined,
    name: "OsmiumCoin",
    precision: 4,
    rounding: 0,
  },
  CAP: {
    code: "CAP",
    symbol: undefined,
    name: "Bottlecaps",
    precision: 4,
    rounding: 0,
  },
  FLT: {
    code: "FLT",
    symbol: undefined,
    name: "FlutterCoin",
    precision: 4,
    rounding: 0,
  },
  KED: {
    code: "KED",
    symbol: undefined,
    name: "Darsek",
    precision: 4,
    rounding: 0,
  },
  PSB: {
    code: "PSB",
    symbol: undefined,
    name: "Pesobit",
    precision: 4,
    rounding: 0,
  },
  LANA: {
    code: "LANA",
    symbol: undefined,
    name: "LanaCoin",
    precision: 4,
    rounding: 0,
  },
  EMD: {
    code: "EMD",
    symbol: undefined,
    name: "Emerald Crypto",
    precision: 4,
    rounding: 0,
  },
  TEK: {
    code: "TEK",
    symbol: undefined,
    name: "TEKcoin",
    precision: 4,
    rounding: 0,
  },
  FRC: {
    code: "FRC",
    symbol: undefined,
    name: "Freicoin",
    precision: 4,
    rounding: 0,
  },
  XHI: {
    code: "XHI",
    symbol: undefined,
    name: "HiCoin",
    precision: 4,
    rounding: 0,
  },
  GB: {
    code: "GB",
    symbol: undefined,
    name: "GoldBlocks",
    precision: 4,
    rounding: 0,
  },
  FRN: {
    code: "FRN",
    symbol: undefined,
    name: "Francs",
    precision: 4,
    rounding: 0,
  },
  MNM: {
    code: "MNM",
    symbol: undefined,
    name: "Mineum",
    precision: 4,
    rounding: 0,
  },
  UNIC: {
    code: "UNIC",
    symbol: undefined,
    name: "UniCoin",
    precision: 4,
    rounding: 0,
  },
  XRA: {
    code: "XRA",
    symbol: undefined,
    name: "Ratecoin",
    precision: 4,
    rounding: 0,
  },
  XJO: {
    code: "XJO",
    symbol: undefined,
    name: "Joulecoin",
    precision: 4,
    rounding: 0,
  },
  REE: {
    code: "REE",
    symbol: undefined,
    name: "ReeCoin",
    precision: 4,
    rounding: 0,
  },
  UNIBURST: {
    code: "UNIBURST",
    symbol: undefined,
    name: "UniBURST",
    precision: 4,
    rounding: 0,
  },
  MAO: {
    code: "MAO",
    symbol: undefined,
    name: "Mao Zedong",
    precision: 4,
    rounding: 0,
  },
  CHESS: {
    code: "CHESS",
    symbol: undefined,
    name: "ChessCoin",
    precision: 4,
    rounding: 0,
  },
  CNNC: {
    code: "CNNC",
    symbol: undefined,
    name: "Cannation",
    precision: 4,
    rounding: 0,
  },
  ELE: {
    code: "ELE",
    symbol: undefined,
    name: "Elementrem",
    precision: 4,
    rounding: 0,
  },
  EUC: {
    code: "EUC",
    symbol: undefined,
    name: "Eurocoin",
    precision: 4,
    rounding: 0,
  },
  "4CHN": {
    code: "4CHN",
    symbol: undefined,
    name: "ChanCoin",
    precision: 4,
    rounding: 0,
  },
  BTCS: {
    code: "BTCS",
    symbol: undefined,
    name: "Bitcoin Scrypt",
    precision: 4,
    rounding: 0,
  },
  VIDZ: {
    code: "VIDZ",
    symbol: undefined,
    name: "PureVidz",
    precision: 4,
    rounding: 0,
  },
  BITSILVER: {
    code: "BITSILVER",
    symbol: undefined,
    name: "bitSilver",
    precision: 4,
    rounding: 0,
  },
  ICN2: {
    code: "ICN2",
    symbol: undefined,
    name: "iCoin",
    precision: 4,
    rounding: 0,
  },
  C2: {
    code: "C2",
    symbol: undefined,
    name: "Coin2.1",
    precision: 4,
    rounding: 0,
  },
  QCN: {
    code: "QCN",
    symbol: undefined,
    name: "QuazarCoin",
    precision: 4,
    rounding: 0,
  },
  PASL: {
    code: "PASL",
    symbol: undefined,
    name: "Pascal Lite",
    precision: 4,
    rounding: 0,
  },
  VAL: {
    code: "VAL",
    symbol: undefined,
    name: "Valorbit",
    precision: 4,
    rounding: 0,
  },
  DUO: {
    code: "DUO",
    symbol: undefined,
    name: "ParallelCoin",
    precision: 4,
    rounding: 0,
  },
  PIP: {
    code: "PIP",
    symbol: undefined,
    name: "PipCoin",
    precision: 4,
    rounding: 0,
  },
  BSTY: {
    code: "BSTY",
    symbol: undefined,
    name: "GlobalBoost-Y",
    precision: 4,
    rounding: 0,
  },
  BLAS: {
    code: "BLAS",
    symbol: undefined,
    name: "BlakeStar",
    precision: 4,
    rounding: 0,
  },
  GTC: {
    code: "GTC",
    symbol: undefined,
    name: "Global Tour Coin",
    precision: 4,
    rounding: 0,
  },
  WAY: {
    code: "WAY",
    symbol: undefined,
    name: "WayGuide",
    precision: 4,
    rounding: 0,
  },
  MOJO: {
    code: "MOJO",
    symbol: undefined,
    name: "MojoCoin",
    precision: 4,
    rounding: 0,
  },
  CAT: {
    code: "CAT",
    symbol: undefined,
    name: "Catcoin",
    precision: 4,
    rounding: 0,
  },
  XGR: {
    code: "XGR",
    symbol: undefined,
    name: "GoldReserve",
    precision: 4,
    rounding: 0,
  },
  YAC: {
    code: "YAC",
    symbol: undefined,
    name: "Yacoin",
    precision: 4,
    rounding: 0,
  },
  DGC: {
    code: "DGC",
    symbol: undefined,
    name: "Digitalcoin",
    precision: 4,
    rounding: 0,
  },
  BLC: {
    code: "BLC",
    symbol: undefined,
    name: "Blakecoin",
    precision: 4,
    rounding: 0,
  },
  MTM: {
    code: "MTM",
    symbol: undefined,
    name: "MTMGaming",
    precision: 4,
    rounding: 0,
  },
  UNI: {
    code: "UNI",
    symbol: undefined,
    name: "Universe",
    precision: 4,
    rounding: 0,
  },
  UNITS: {
    code: "UNITS",
    symbol: undefined,
    name: "GameUnits",
    precision: 4,
    rounding: 0,
  },
  XCT: {
    code: "XCT",
    symbol: undefined,
    name: "C-Bit",
    precision: 4,
    rounding: 0,
  },
  XPD: {
    code: "XPD",
    symbol: undefined,
    name: "PetroDollar",
    precision: 4,
    rounding: 0,
  },
  FUNK: {
    code: "FUNK",
    symbol: undefined,
    name: "The Cypherfunks",
    precision: 4,
    rounding: 0,
  },
  KIC: {
    code: "KIC",
    symbol: undefined,
    name: "KibiCoin",
    precision: 4,
    rounding: 0,
  },
  CJ: {
    code: "CJ",
    symbol: undefined,
    name: "Cryptojacks",
    precision: 4,
    rounding: 0,
  },
  SWING: {
    code: "SWING",
    symbol: undefined,
    name: "Swing",
    precision: 4,
    rounding: 0,
  },
  TGC: {
    code: "TGC",
    symbol: undefined,
    name: "Tigercoin",
    precision: 4,
    rounding: 0,
  },
  UNIT: {
    code: "UNIT",
    symbol: undefined,
    name: "Universal Cur...",
    precision: 4,
    rounding: 0,
  },
  MCRN: {
    code: "MCRN",
    symbol: undefined,
    name: "MACRON",
    precision: 4,
    rounding: 0,
  },
  BTWTY: {
    code: "BTWTY",
    symbol: undefined,
    name: "Bit20",
    precision: 4,
    rounding: 0,
  },
  SPEX: {
    code: "SPEX",
    symbol: undefined,
    name: "SproutsExtreme",
    precision: 4,
    rounding: 0,
  },
  B3: {
    code: "B3",
    symbol: undefined,
    name: "B3Coin",
    precision: 4,
    rounding: 0,
  },
  BITEUR: {
    code: "BITEUR",
    symbol: undefined,
    name: "bitEUR",
    precision: 4,
    rounding: 0,
  },
  PXI: {
    code: "PXI",
    symbol: undefined,
    name: "Prime-XI",
    precision: 4,
    rounding: 0,
  },
  JET: {
    code: "JET",
    symbol: undefined,
    name: "JetCoin",
    precision: 4,
    rounding: 0,
  },
  HMP: {
    code: "HMP",
    symbol: undefined,
    name: "HempCoin",
    precision: 4,
    rounding: 0,
  },
  RUPX: {
    code: "RUPX",
    symbol: undefined,
    name: "Rupaya",
    precision: 4,
    rounding: 0,
  },
  BITGOLD: {
    code: "BITGOLD",
    symbol: undefined,
    name: "bitGold",
    precision: 4,
    rounding: 0,
  },
  BERN: {
    code: "BERN",
    symbol: undefined,
    name: "BERNcash",
    precision: 4,
    rounding: 0,
  },
  WMC: {
    code: "WMC",
    symbol: undefined,
    name: "WMCoin",
    precision: 4,
    rounding: 0,
  },
  STV: {
    code: "STV",
    symbol: undefined,
    name: "Sativacoin",
    precision: 4,
    rounding: 0,
  },
  EVIL: {
    code: "EVIL",
    symbol: undefined,
    name: "Evil Coin",
    precision: 4,
    rounding: 0,
  },
  NYAN: {
    code: "NYAN",
    symbol: undefined,
    name: "Nyancoin",
    precision: 4,
    rounding: 0,
  },
  LTB: {
    code: "LTB",
    symbol: undefined,
    name: "LiteBar",
    precision: 4,
    rounding: 0,
  },
  J: {
    code: "J",
    symbol: undefined,
    name: "Joincoin",
    precision: 4,
    rounding: 0,
  },
  KURT: {
    code: "KURT",
    symbol: undefined,
    name: "Kurrent",
    precision: 4,
    rounding: 0,
  },
  KAYI: {
    code: "KAYI",
    symbol: undefined,
    name: "Kayi",
    precision: 4,
    rounding: 0,
  },
  CYP: {
    code: "CYP",
    symbol: undefined,
    name: "Cypher",
    precision: 4,
    rounding: 0,
  },
  XPTX: {
    code: "XPTX",
    symbol: undefined,
    name: "PlatinumBAR",
    precision: 4,
    rounding: 0,
  },
  SCORE: {
    code: "SCORE",
    symbol: undefined,
    name: "Scorecoin",
    precision: 4,
    rounding: 0,
  },
  XLR: {
    code: "XLR",
    symbol: undefined,
    name: "Solaris",
    precision: 4,
    rounding: 0,
  },
  KUSH: {
    code: "KUSH",
    symbol: undefined,
    name: "KushCoin",
    precision: 4,
    rounding: 0,
  },
  BOLI: {
    code: "BOLI",
    symbol: undefined,
    name: "Bolivarcoin",
    precision: 4,
    rounding: 0,
  },
  FLAX: {
    code: "FLAX",
    symbol: undefined,
    name: "Flaxscript",
    precision: 4,
    rounding: 0,
  },
  RED: {
    code: "RED",
    symbol: undefined,
    name: "RedCoin",
    precision: 4,
    rounding: 0,
  },
  PR: {
    code: "PR",
    symbol: undefined,
    name: "Prototanium",
    precision: 4,
    rounding: 0,
  },
  BTCR: {
    code: "BTCR",
    symbol: undefined,
    name: "Bitcurrency",
    precision: 4,
    rounding: 0,
  },
  PRC: {
    code: "PRC",
    symbol: undefined,
    name: "PRCoin",
    precision: 4,
    rounding: 0,
  },
  TSE: {
    code: "TSE",
    symbol: undefined,
    name: "Tattoocoin (S...",
    precision: 4,
    rounding: 0,
  },
  GRT: {
    code: "GRT",
    symbol: undefined,
    name: "Grantcoin",
    precision: 4,
    rounding: 0,
  },
  VEC2: {
    code: "VEC2",
    symbol: undefined,
    name: "Vector",
    precision: 4,
    rounding: 0,
  },
  ICOB: {
    code: "ICOB",
    symbol: undefined,
    name: "ICOBID",
    precision: 4,
    rounding: 0,
  },
  SOJ: {
    code: "SOJ",
    symbol: undefined,
    name: "Sojourn",
    precision: 4,
    rounding: 0,
  },
  GPU: {
    code: "GPU",
    symbol: undefined,
    name: "GPU Coin",
    precision: 4,
    rounding: 0,
  },
  CRX: {
    code: "CRX",
    symbol: undefined,
    name: "Chronos",
    precision: 4,
    rounding: 0,
  },
  DIBC: {
    code: "DIBC",
    symbol: undefined,
    name: "DIBCOIN",
    precision: 4,
    rounding: 0,
  },
  XRE: {
    code: "XRE",
    symbol: undefined,
    name: "RevolverCoin",
    precision: 4,
    rounding: 0,
  },
  BIGUP: {
    code: "BIGUP",
    symbol: undefined,
    name: "BigUp",
    precision: 4,
    rounding: 0,
  },
  BBP: {
    code: "BBP",
    symbol: undefined,
    name: "BiblePay",
    precision: 4,
    rounding: 0,
  },
  JIN: {
    code: "JIN",
    symbol: undefined,
    name: "Jin Coin",
    precision: 4,
    rounding: 0,
  },
  SOIL: {
    code: "SOIL",
    symbol: undefined,
    name: "SOILcoin",
    precision: 4,
    rounding: 0,
  },
  ACOIN: {
    code: "ACOIN",
    symbol: undefined,
    name: "Acoin",
    precision: 4,
    rounding: 0,
  },
  SLG: {
    code: "SLG",
    symbol: undefined,
    name: "Sterlingcoin",
    precision: 4,
    rounding: 0,
  },
  HONEY: {
    code: "HONEY",
    symbol: undefined,
    name: "Honey",
    precision: 4,
    rounding: 0,
  },
  MAR: {
    code: "MAR",
    symbol: undefined,
    name: "Marijuanacoin",
    precision: 4,
    rounding: 0,
  },
  MAD: {
    code: "MAD",
    symbol: undefined,
    name: "SatoshiMadness",
    precision: 4,
    rounding: 0,
  },
  PX: {
    code: "PX",
    symbol: undefined,
    name: "PX",
    precision: 4,
    rounding: 0,
  },
  ARI: {
    code: "ARI",
    symbol: undefined,
    name: "Aricoin",
    precision: 4,
    rounding: 0,
  },
  SRC: {
    code: "SRC",
    symbol: undefined,
    name: "SecureCoin",
    precision: 4,
    rounding: 0,
  },
  SPACE: {
    code: "SPACE",
    symbol: undefined,
    name: "SpaceCoin",
    precision: 4,
    rounding: 0,
  },
  RUP: {
    code: "RUP",
    symbol: undefined,
    name: "Rupee",
    precision: 4,
    rounding: 0,
  },
  DALC: {
    code: "DALC",
    symbol: undefined,
    name: "Dalecoin",
    precision: 4,
    rounding: 0,
  },
  GUN: {
    code: "GUN",
    symbol: undefined,
    name: "Guncoin",
    precision: 4,
    rounding: 0,
  },
  MARS: {
    code: "MARS",
    symbol: undefined,
    name: "Marscoin",
    precision: 4,
    rounding: 0,
  },
  CORG: {
    code: "CORG",
    symbol: undefined,
    name: "CorgiCoin",
    precision: 4,
    rounding: 0,
  },
  ADCN: {
    code: "ADCN",
    symbol: undefined,
    name: "Asiadigicoin",
    precision: 4,
    rounding: 0,
  },
  IMS: {
    code: "IMS",
    symbol: undefined,
    name: "Independent M...",
    precision: 4,
    rounding: 0,
  },
  XCO: {
    code: "XCO",
    symbol: undefined,
    name: "X-Coin",
    precision: 4,
    rounding: 0,
  },
  PHS: {
    code: "PHS",
    symbol: undefined,
    name: "Philosopher S...",
    precision: 4,
    rounding: 0,
  },
  ARG: {
    code: "ARG",
    symbol: undefined,
    name: "Argentum",
    precision: 4,
    rounding: 0,
  },
  ARCO: {
    code: "ARCO",
    symbol: undefined,
    name: "AquariusCoin",
    precision: 4,
    rounding: 0,
  },
  SCRT: {
    code: "SCRT",
    symbol: undefined,
    name: "SecretCoin",
    precision: 4,
    rounding: 0,
  },
  GPL: {
    code: "GPL",
    symbol: undefined,
    name: "Gold Pressed ...",
    precision: 4,
    rounding: 0,
  },
  SPT: {
    code: "SPT",
    symbol: undefined,
    name: "Spots",
    precision: 4,
    rounding: 0,
  },
  SLING: {
    code: "SLING",
    symbol: undefined,
    name: "Sling",
    precision: 4,
    rounding: 0,
  },
  MEOW: {
    code: "MEOW",
    symbol: undefined,
    name: "Kittehcoin",
    precision: 4,
    rounding: 0,
  },
  GAP: {
    code: "GAP",
    symbol: undefined,
    name: "Gapcoin",
    precision: 4,
    rounding: 0,
  },
  ASAFE2: {
    code: "ASAFE2",
    symbol: undefined,
    name: "AllSafe",
    precision: 4,
    rounding: 0,
  },
  RBT: {
    code: "RBT",
    symbol: undefined,
    name: "Rimbit",
    precision: 4,
    rounding: 0,
  },
  WORM: {
    code: "WORM",
    symbol: undefined,
    name: "HealthyWormCoin",
    precision: 4,
    rounding: 0,
  },
  PUTIC: {
    code: "PUTIC",
    symbol: undefined,
    name: "Putin Classic",
    precision: 4,
    rounding: 0,
  },
  TOR: {
    code: "TOR",
    symbol: undefined,
    name: "Torcoin",
    precision: 4,
    rounding: 0,
  },
  UET: {
    code: "UET",
    symbol: undefined,
    name: "Useless Ether...",
    precision: 4,
    rounding: 0,
  },
  GCC: {
    code: "GCC",
    symbol: undefined,
    name: "GuccioneCoin",
    precision: 4,
    rounding: 0,
  },
  BTPL: {
    code: "BTPL",
    symbol: undefined,
    name: "Bitcoin Planet",
    precision: 4,
    rounding: 0,
  },
  BCF: {
    code: "BCF",
    symbol: undefined,
    name: "BitcoinFast",
    precision: 4,
    rounding: 0,
  },
  ALL: {
    code: "ALL",
    symbol: undefined,
    name: "Allion",
    precision: 4,
    rounding: 0,
  },
  ZNY: {
    code: "ZNY",
    symbol: undefined,
    name: "Bitzeny",
    precision: 4,
    rounding: 0,
  },
  MSCN: {
    code: "MSCN",
    symbol: undefined,
    name: "Master Swiscoin",
    precision: 4,
    rounding: 0,
  },
  BOAT: {
    code: "BOAT",
    symbol: undefined,
    name: "Doubloon",
    precision: 4,
    rounding: 0,
  },
  CREVA: {
    code: "CREVA",
    symbol: undefined,
    name: "CrevaCoin",
    precision: 4,
    rounding: 0,
  },
  BIP: {
    code: "BIP",
    symbol: undefined,
    name: "BipCoin",
    precision: 4,
    rounding: 0,
  },
  BLRY: {
    code: "BLRY",
    symbol: undefined,
    name: "BillaryCoin",
    precision: 4,
    rounding: 0,
  },
  IOU: {
    code: "IOU",
    symbol: undefined,
    name: "IOU1",
    precision: 4,
    rounding: 0,
  },
  BOST: {
    code: "BOST",
    symbol: undefined,
    name: "BoostCoin",
    precision: 4,
    rounding: 0,
  },
  GLT: {
    code: "GLT",
    symbol: undefined,
    name: "GlobalToken",
    precision: 4,
    rounding: 0,
  },
  CXT: {
    code: "CXT",
    symbol: undefined,
    name: "Coinonat",
    precision: 4,
    rounding: 0,
  },
  KLC: {
    code: "KLC",
    symbol: undefined,
    name: "KiloCoin",
    precision: 4,
    rounding: 0,
  },
  QTL: {
    code: "QTL",
    symbol: undefined,
    name: "Quatloo",
    precision: 4,
    rounding: 0,
  },
  EVO: {
    code: "EVO",
    symbol: undefined,
    name: "Evotion",
    precision: 4,
    rounding: 0,
  },
  MI: {
    code: "MI",
    symbol: undefined,
    name: "Xiaomicoin",
    precision: 4,
    rounding: 0,
  },
  NEVA: {
    code: "NEVA",
    symbol: undefined,
    name: "NevaCoin",
    precision: 4,
    rounding: 0,
  },
  WYV: {
    code: "WYV",
    symbol: undefined,
    name: "Wyvern",
    precision: 4,
    rounding: 0,
  },
  HAL: {
    code: "HAL",
    symbol: undefined,
    name: "Halcyon",
    precision: 4,
    rounding: 0,
  },
  BUMBA: {
    code: "BUMBA",
    symbol: undefined,
    name: "BumbaCoin",
    precision: 4,
    rounding: 0,
  },
  CPN: {
    code: "CPN",
    symbol: undefined,
    name: "CompuCoin",
    precision: 4,
    rounding: 0,
  },
  DBTC: {
    code: "DBTC",
    symbol: undefined,
    name: "Debitcoin",
    precision: 4,
    rounding: 0,
  },
  PHO: {
    code: "PHO",
    symbol: undefined,
    name: "Photon",
    precision: 4,
    rounding: 0,
  },
  FRK: {
    code: "FRK",
    symbol: undefined,
    name: "Franko",
    precision: 4,
    rounding: 0,
  },
  ERY: {
    code: "ERY",
    symbol: undefined,
    name: "Eryllium",
    precision: 4,
    rounding: 0,
  },
  GP: {
    code: "GP",
    symbol: undefined,
    name: "GoldPieces",
    precision: 4,
    rounding: 0,
  },
  XCRE: {
    code: "XCRE",
    symbol: undefined,
    name: "Creatio",
    precision: 4,
    rounding: 0,
  },
  MAY: {
    code: "MAY",
    symbol: undefined,
    name: "Theresa May Coin",
    precision: 4,
    rounding: 0,
  },
  ZMC: {
    code: "ZMC",
    symbol: undefined,
    name: "ZetaMicron",
    precision: 4,
    rounding: 0,
  },
  HXX: {
    code: "HXX",
    symbol: undefined,
    name: "Hexx",
    precision: 4,
    rounding: 0,
  },
  AMMO: {
    code: "AMMO",
    symbol: undefined,
    name: "Ammo Rewards",
    precision: 4,
    rounding: 0,
  },
  GBC: {
    code: "GBC",
    symbol: undefined,
    name: "GBCGoldCoin",
    precision: 4,
    rounding: 0,
  },
  POP: {
    code: "POP",
    symbol: undefined,
    name: "PopularCoin",
    precision: 4,
    rounding: 0,
  },
  PONZI: {
    code: "PONZI",
    symbol: undefined,
    name: "PonziCoin",
    precision: 4,
    rounding: 0,
  },
  SLEVIN: {
    code: "SLEVIN",
    symbol: undefined,
    name: "Slevin",
    precision: 4,
    rounding: 0,
  },
  ANTI: {
    code: "ANTI",
    symbol: undefined,
    name: "AntiBitcoin",
    precision: 4,
    rounding: 0,
  },
  URC: {
    code: "URC",
    symbol: undefined,
    name: "Unrealcoin",
    precision: 4,
    rounding: 0,
  },
  MST: {
    code: "MST",
    symbol: undefined,
    name: "MustangCoin",
    precision: 4,
    rounding: 0,
  },
  DRS: {
    code: "DRS",
    symbol: undefined,
    name: "Digital Rupees",
    precision: 4,
    rounding: 0,
  },
  ONX: {
    code: "ONX",
    symbol: undefined,
    name: "Onix",
    precision: 4,
    rounding: 0,
  },
  URO: {
    code: "URO",
    symbol: undefined,
    name: "Uro",
    precision: 4,
    rounding: 0,
  },
  RPC: {
    code: "RPC",
    symbol: undefined,
    name: "RonPaulCoin",
    precision: 4,
    rounding: 0,
  },
  BIOS: {
    code: "BIOS",
    symbol: undefined,
    name: "BiosCrypto",
    precision: 4,
    rounding: 0,
  },
  BNX: {
    code: "BNX",
    symbol: undefined,
    name: "BnrtxCoin",
    precision: 4,
    rounding: 0,
  },
  ATX: {
    code: "ATX",
    symbol: undefined,
    name: "Artex Coin",
    precision: 4,
    rounding: 0,
  },
  BQC: {
    code: "BQC",
    symbol: undefined,
    name: "BBQCoin",
    precision: 4,
    rounding: 0,
  },
  CTO: {
    code: "CTO",
    symbol: undefined,
    name: "Crypto",
    precision: 4,
    rounding: 0,
  },
  ARB: {
    code: "ARB",
    symbol: undefined,
    name: "ARbit",
    precision: 4,
    rounding: 0,
  },
  SOON: {
    code: "SOON",
    symbol: undefined,
    name: "SoonCoin",
    precision: 4,
    rounding: 0,
  },
  SOCC: {
    code: "SOCC",
    symbol: undefined,
    name: "SocialCoin",
    precision: 4,
    rounding: 0,
  },
  VIP: {
    code: "VIP",
    symbol: undefined,
    name: "VIP Tokens",
    precision: 4,
    rounding: 0,
  },
  CTIC2: {
    code: "CTIC2",
    symbol: undefined,
    name: "Coimatic 2.0",
    precision: 4,
    rounding: 0,
  },
  CAB: {
    code: "CAB",
    symbol: undefined,
    name: "Cabbage",
    precision: 4,
    rounding: 0,
  },
  SONG: {
    code: "SONG",
    symbol: undefined,
    name: "SongCoin",
    precision: 4,
    rounding: 0,
  },
  BENJI: {
    code: "BENJI",
    symbol: undefined,
    name: "BenjiRolls",
    precision: 4,
    rounding: 0,
  },
  FRAZ: {
    code: "FRAZ",
    symbol: undefined,
    name: "Frazcoin",
    precision: 4,
    rounding: 0,
  },
  FIRE: {
    code: "FIRE",
    symbol: undefined,
    name: "Firecoin",
    precision: 4,
    rounding: 0,
  },
  IMX: {
    code: "IMX",
    symbol: undefined,
    name: "Impact",
    precision: 4,
    rounding: 0,
  },
  BVC: {
    code: "BVC",
    symbol: undefined,
    name: "BeaverCoin",
    precision: 4,
    rounding: 0,
  },
  LEA: {
    code: "LEA",
    symbol: undefined,
    name: "LeaCoin",
    precision: 4,
    rounding: 0,
  },
  CESC: {
    code: "CESC",
    symbol: undefined,
    name: "CryptoEscudo",
    precision: 4,
    rounding: 0,
  },
  PLNC: {
    code: "PLNC",
    symbol: undefined,
    name: "PLNcoin",
    precision: 4,
    rounding: 0,
  },
  STEPS: {
    code: "STEPS",
    symbol: undefined,
    name: "Steps",
    precision: 4,
    rounding: 0,
  },
  ACP: {
    code: "ACP",
    symbol: undefined,
    name: "AnarchistsPrime",
    precision: 4,
    rounding: 0,
  },
  VTA: {
    code: "VTA",
    symbol: undefined,
    name: "Virtacoin",
    precision: 4,
    rounding: 0,
  },
  PULSE: {
    code: "PULSE",
    symbol: undefined,
    name: "Pulse",
    precision: 4,
    rounding: 0,
  },
  MND: {
    code: "MND",
    symbol: undefined,
    name: "MindCoin",
    precision: 4,
    rounding: 0,
  },
  JWL: {
    code: "JWL",
    symbol: undefined,
    name: "Jewels",
    precision: 4,
    rounding: 0,
  },
  RIDE: {
    code: "RIDE",
    symbol: undefined,
    name: "Ride My Car",
    precision: 4,
    rounding: 0,
  },
  GBT: {
    code: "GBT",
    symbol: undefined,
    name: "GameBet Coin",
    precision: 4,
    rounding: 0,
  },
  CWXT: {
    code: "CWXT",
    symbol: undefined,
    name: "CryptoWorldX ...",
    precision: 4,
    rounding: 0,
  },
  FLVR: {
    code: "FLVR",
    symbol: undefined,
    name: "FlavorCoin",
    precision: 4,
    rounding: 0,
  },
  ECO: {
    code: "ECO",
    symbol: undefined,
    name: "EcoCoin",
    precision: 4,
    rounding: 0,
  },
  G3N: {
    code: "G3N",
    symbol: undefined,
    name: "G3N",
    precision: 4,
    rounding: 0,
  },
  TAGR: {
    code: "TAGR",
    symbol: undefined,
    name: "TAGRcoin",
    precision: 4,
    rounding: 0,
  },
  OFF: {
    code: "OFF",
    symbol: undefined,
    name: "Cthulhu Offer...",
    precision: 4,
    rounding: 0,
  },
  BTQ: {
    code: "BTQ",
    symbol: undefined,
    name: "BitQuark",
    precision: 4,
    rounding: 0,
  },
  MTLMC3: {
    code: "MTLMC3",
    symbol: undefined,
    name: "Metal Music Coin",
    precision: 4,
    rounding: 0,
  },
  ZYD: {
    code: "ZYD",
    symbol: undefined,
    name: "Zayedcoin",
    precision: 4,
    rounding: 0,
  },
  DOLLAR: {
    code: "DOLLAR",
    symbol: undefined,
    name: "Dollar Online",
    precision: 4,
    rounding: 0,
  },
  LUNA: {
    code: "LUNA",
    symbol: undefined,
    name: "Luna Coin",
    precision: 4,
    rounding: 0,
  },
  XBTS: {
    code: "XBTS",
    symbol: undefined,
    name: "Beatcoin",
    precision: 4,
    rounding: 0,
  },
  MILO: {
    code: "MILO",
    symbol: undefined,
    name: "MiloCoin",
    precision: 4,
    rounding: 0,
  },
  BRIA: {
    code: "BRIA",
    symbol: undefined,
    name: "BriaCoin",
    precision: 4,
    rounding: 0,
  },
  DES: {
    code: "DES",
    symbol: undefined,
    name: "Destiny",
    precision: 4,
    rounding: 0,
  },
  TAJ: {
    code: "TAJ",
    symbol: undefined,
    name: "TajCoin",
    precision: 4,
    rounding: 0,
  },
  COAL: {
    code: "COAL",
    symbol: undefined,
    name: "BitCoal",
    precision: 4,
    rounding: 0,
  },
  SFC: {
    code: "SFC",
    symbol: undefined,
    name: "Solarflarecoin",
    precision: 4,
    rounding: 0,
  },
  BSTAR: {
    code: "BSTAR",
    symbol: undefined,
    name: "Blackstar",
    precision: 4,
    rounding: 0,
  },
  ORLY: {
    code: "ORLY",
    symbol: undefined,
    name: "Orlycoin",
    precision: 4,
    rounding: 0,
  },
  CMT: {
    code: "CMT",
    symbol: undefined,
    name: "Comet",
    precision: 4,
    rounding: 0,
  },
  AGLC: {
    code: "AGLC",
    symbol: undefined,
    name: "AgrolifeCoin",
    precision: 4,
    rounding: 0,
  },
  DLISK: {
    code: "DLISK",
    symbol: undefined,
    name: "DAPPSTER",
    precision: 4,
    rounding: 0,
  },
  ICON: {
    code: "ICON",
    symbol: undefined,
    name: "Iconic",
    precision: 4,
    rounding: 0,
  },
  QBK: {
    code: "QBK",
    symbol: undefined,
    name: "Qibuck Asset",
    precision: 4,
    rounding: 0,
  },
  VPRC: {
    code: "VPRC",
    symbol: undefined,
    name: "VapersCoin",
    precision: 4,
    rounding: 0,
  },
  IBANK: {
    code: "IBANK",
    symbol: undefined,
    name: "iBank",
    precision: 4,
    rounding: 0,
  },
  VLTC: {
    code: "VLTC",
    symbol: undefined,
    name: "Vault Coin",
    precision: 4,
    rounding: 0,
  },
  NRO: {
    code: "NRO",
    symbol: undefined,
    name: "Neuro",
    precision: 4,
    rounding: 0,
  },
  SCS: {
    code: "SCS",
    symbol: undefined,
    name: "Speedcash",
    precision: 4,
    rounding: 0,
  },
  HVCO: {
    code: "HVCO",
    symbol: undefined,
    name: "High Voltage",
    precision: 4,
    rounding: 0,
  },
  VRS: {
    code: "VRS",
    symbol: undefined,
    name: "Veros",
    precision: 4,
    rounding: 0,
  },
  LBTC: {
    code: "LBTC",
    symbol: undefined,
    name: "LiteBitcoin",
    precision: 4,
    rounding: 0,
  },
  WARP: {
    code: "WARP",
    symbol: undefined,
    name: "WARP",
    precision: 4,
    rounding: 0,
  },
  TRADE2: {
    code: "TRADE2",
    symbol: undefined,
    name: "TradecoinV2",
    precision: 4,
    rounding: 0,
  },
  LTCR: {
    code: "LTCR",
    symbol: undefined,
    name: "Litecred",
    precision: 4,
    rounding: 0,
  },
  BLZ: {
    code: "BLZ",
    symbol: undefined,
    name: "BlazeCoin",
    precision: 4,
    rounding: 0,
  },
  EGO: {
    code: "EGO",
    symbol: undefined,
    name: "EGO",
    precision: 4,
    rounding: 0,
  },
  DPAY: {
    code: "DPAY",
    symbol: undefined,
    name: "DPAY",
    precision: 4,
    rounding: 0,
  },
  FUZZ: {
    code: "FUZZ",
    symbol: undefined,
    name: "FuzzBalls",
    precision: 4,
    rounding: 0,
  },
  KNC: {
    code: "KNC",
    symbol: undefined,
    name: "KingN Coin",
    precision: 4,
    rounding: 0,
  },
  CASH: {
    code: "CASH",
    symbol: undefined,
    name: "Cashcoin",
    precision: 4,
    rounding: 0,
  },
  IMPS: {
    code: "IMPS",
    symbol: undefined,
    name: "ImpulseCoin",
    precision: 4,
    rounding: 0,
  },
  XOC: {
    code: "XOC",
    symbol: undefined,
    name: "Xonecoin",
    precision: 4,
    rounding: 0,
  },
  MNC: {
    code: "MNC",
    symbol: undefined,
    name: "MantraCoin",
    precision: 4,
    rounding: 0,
  },
  PRX: {
    code: "PRX",
    symbol: undefined,
    name: "Printerium",
    precision: 4,
    rounding: 0,
  },
  BSC: {
    code: "BSC",
    symbol: undefined,
    name: "BowsCoin",
    precision: 4,
    rounding: 0,
  },
  LIR: {
    code: "LIR",
    symbol: undefined,
    name: "LetItRide",
    precision: 4,
    rounding: 0,
  },
  CRT: {
    code: "CRT",
    symbol: undefined,
    name: "CRTCoin",
    precision: 4,
    rounding: 0,
  },
  SH: {
    code: "SH",
    symbol: undefined,
    name: "Shilling",
    precision: 4,
    rounding: 0,
  },
  ZNE: {
    code: "ZNE",
    symbol: undefined,
    name: "Zonecoin",
    precision: 4,
    rounding: 0,
  },
  RSGP: {
    code: "RSGP",
    symbol: undefined,
    name: "RSGPcoin",
    precision: 4,
    rounding: 0,
  },
  CONX: {
    code: "CONX",
    symbol: undefined,
    name: "Concoin",
    precision: 4,
    rounding: 0,
  },
  WEX: {
    code: "WEX",
    symbol: undefined,
    name: "Wexcoin",
    precision: 4,
    rounding: 0,
  },
  XRC: {
    code: "XRC",
    symbol: undefined,
    name: "Rawcoin",
    precision: 4,
    rounding: 0,
  },
  JOBS: {
    code: "JOBS",
    symbol: undefined,
    name: "JobsCoin",
    precision: 4,
    rounding: 0,
  },
  ALTC: {
    code: "ALTC",
    symbol: undefined,
    name: "Antilitecoin",
    precision: 4,
    rounding: 0,
  },
  LVPS: {
    code: "LVPS",
    symbol: undefined,
    name: "LevoPlus",
    precision: 4,
    rounding: 0,
  },
  "1CR": {
    code: "1CR",
    symbol: undefined,
    name: "1CRedit",
    precision: 4,
    rounding: 0,
  },
  ARGUS: {
    code: "ARGUS",
    symbol: undefined,
    name: "Argus",
    precision: 4,
    rounding: 0,
  },
  GEERT: {
    code: "GEERT",
    symbol: undefined,
    name: "GeertCoin",
    precision: 4,
    rounding: 0,
  },
  JIO: {
    code: "JIO",
    symbol: undefined,
    name: "JIO Token",
    precision: 4,
    rounding: 0,
  },
  EBT: {
    code: "EBT",
    symbol: undefined,
    name: "Ebittree Coin",
    precision: 4,
    rounding: 0,
  },
  OCEAN: {
    code: "OCEAN",
    symbol: undefined,
    name: "BurstOcean",
    precision: 4,
    rounding: 0,
  },
  ABN: {
    code: "ABN",
    symbol: undefined,
    name: "Abncoin",
    precision: 4,
    rounding: 0,
  },
  APW: {
    code: "APW",
    symbol: undefined,
    name: "AppleCoin",
    precision: 4,
    rounding: 0,
  },
  VOLT: {
    code: "VOLT",
    symbol: undefined,
    name: "Bitvolt",
    precision: 4,
    rounding: 0,
  },
  SDP: {
    code: "SDP",
    symbol: undefined,
    name: "SydPak",
    precision: 4,
    rounding: 0,
  },
  MGM: {
    code: "MGM",
    symbol: undefined,
    name: "Magnum",
    precision: 4,
    rounding: 0,
  },
  BIOB: {
    code: "BIOB",
    symbol: undefined,
    name: "BioBar",
    precision: 4,
    rounding: 0,
  },
  P7C: {
    code: "P7C",
    symbol: undefined,
    name: "P7Coin",
    precision: 4,
    rounding: 0,
  },
  NODC: {
    code: "NODC",
    symbol: undefined,
    name: "NodeCoin",
    precision: 4,
    rounding: 0,
  },
  CF: {
    code: "CF",
    symbol: undefined,
    name: "Californium",
    precision: 4,
    rounding: 0,
  },
  LEX: {
    code: "LEX",
    symbol: undefined,
    name: "Lex4All",
    precision: 4,
    rounding: 0,
  },
  XNG: {
    code: "XNG",
    symbol: undefined,
    name: "Enigma",
    precision: 4,
    rounding: 0,
  },
  HMC: {
    code: "HMC",
    symbol: undefined,
    name: "HarmonyCoin",
    precision: 4,
    rounding: 0,
  },
  ULA: {
    code: "ULA",
    symbol: undefined,
    name: "Ulatech",
    precision: 4,
    rounding: 0,
  },
  DRAGON: {
    code: "DRAGON",
    symbol: undefined,
    name: "BTCDragon",
    precision: 4,
    rounding: 0,
  },
  ENV: {
    code: "ENV",
    symbol: undefined,
    name: "Environ",
    precision: 4,
    rounding: 0,
  },
  FDC: {
    code: "FDC",
    symbol: undefined,
    name: "Future Digita...",
    precision: 4,
    rounding: 0,
  },
  PIZZA: {
    code: "PIZZA",
    symbol: undefined,
    name: "PizzaCoin",
    precision: 4,
    rounding: 0,
  },
  DGCS: {
    code: "DGCS",
    symbol: undefined,
    name: "Digital Credits",
    precision: 4,
    rounding: 0,
  },
  PWR: {
    code: "PWR",
    symbol: undefined,
    name: "Powercoin",
    precision: 4,
    rounding: 0,
  },
  ETB: {
    code: "ETB",
    symbol: undefined,
    name: "Ethbits",
    precision: 4,
    rounding: 0,
  },
  MUG: {
    code: "MUG",
    symbol: undefined,
    name: "MikeTheMug",
    precision: 4,
    rounding: 0,
  },
  DMB: {
    code: "DMB",
    symbol: undefined,
    name: "Digital Money...",
    precision: 4,
    rounding: 0,
  },
  XEN: {
    code: "XEN",
    symbol: undefined,
    name: "Xenixcoin",
    precision: 4,
    rounding: 0,
  },
  CALC: {
    code: "CALC",
    symbol: undefined,
    name: "CaliphCoin",
    precision: 4,
    rounding: 0,
  },
};
